<script setup lang="ts">
import type { EChartsCoreOption } from "echarts/core";
import { appNavItems } from "~/utils/app-nav";
import { resolveApiErrorMessage } from "~/utils/api-errors";
import { formatAppDateTime } from "~/utils/date-format";

type Detail = {
	store: { id: string; name: string; store_type: string; currency: string; business_day_start_minutes: number };
	dashboard: any; stock: any; purchasing: any; products: any;
};
const route = useRoute();
const { apiFetch } = useApiClient();
const preset = ref(String(route.query.preset || "today"));
const dateFrom = ref(String(route.query.date_from || ""));
const dateTo = ref(String(route.query.date_to || ""));
const loading = ref(true);
const refreshing = ref(false);
const error = ref("");
const report = ref<Detail | null>(null);
const tabs = [
	{ id: "sales", label: "ຍອດຂາຍ" },
	{ id: "products", label: "ສິນຄ້າ" },
	{ id: "stock", label: "ສະຕັອກ" },
	{ id: "purchasing", label: "ການຈັດຊື້" },
	{ id: "promotions", label: "ໂປຣໂມຊັນ" },
	{ id: "operations", label: "ການດຳເນີນງານ" },
];
const activeTab = ref("sales");
const presets = [ { id: "today", label: "ມື້ນີ້" }, { id: "yesterday", label: "ມື້ວານ" }, { id: "this_week", label: "ອາທິດນີ້" }, { id: "last_week", label: "ອາທິດກ່ອນ" }, { id: "this_month", label: "ເດືອນນີ້" }, { id: "last_month", label: "ເດືອນກ່ອນ" }, { id: "custom", label: "ກຳນົດເອງ" } ];
const currency = computed(() => report.value?.store.currency || "LAK");
function money(value: number) {
	const formatted = new Intl.NumberFormat("lo-LA", { maximumFractionDigits: 0 }).format(value || 0);
	return currency.value === "LAK" ? `${formatted}₭` : new Intl.NumberFormat("lo-LA", { style: "currency", currency: currency.value, maximumFractionDigits: 0 }).format(value || 0);
}
function number(value: number) { return new Intl.NumberFormat("lo-LA").format(value || 0); }
const compactNumber = (value: number) => new Intl.NumberFormat("lo-LA", { notation: "compact", maximumFractionDigits: 1 }).format(value || 0);
const commonTooltip = { trigger: "axis", axisPointer: { type: "cross" }, valueFormatter: (value: unknown) => money(Number(value)) };
const salesOption = computed<EChartsCoreOption>(() => ({
	color: ["#10b981", "#3b82f6"], tooltip: commonTooltip, legend: { bottom: 0, data: ["ຍອດຂາຍ", "ຈຳນວນບິນ"] }, grid: { left: 12, right: 18, top: 24, bottom: 54, containLabel: true },
	xAxis: { type: "category", data: report.value?.dashboard.sales_series.map((item: any) => item.label) || [] }, yAxis: [{ type: "value", axisLabel: { formatter: compactNumber }, splitLine: { lineStyle: { color: "#f5f5f4" } } }, { type: "value", splitLine: { show: false } }],
	series: [{ name: "ຍອດຂາຍ", type: "line", smooth: true, symbol: "circle", symbolSize: 7, areaStyle: { color: "rgba(16,185,129,.14)" }, data: report.value?.dashboard.sales_series.map((item: any) => item.revenue) || [] }, { name: "ຈຳນວນບິນ", type: "bar", yAxisIndex: 1, barMaxWidth: 18, itemStyle: { color: "rgba(59,130,246,.35)", borderRadius: [4, 4, 0, 0] }, data: report.value?.dashboard.sales_series.map((item: any) => item.bill_count) || [] }],
}));
const profitOption = computed<EChartsCoreOption>(() => ({
	color: ["#f59e0b", "#10b981", "#a8a29e"], tooltip: commonTooltip, legend: { bottom: 0 }, grid: { left: 10, right: 10, top: 24, bottom: 48, containLabel: true }, xAxis: { type: "category", data: report.value?.dashboard.sales_series.map((item: any) => item.label) || [] }, yAxis: { type: "value", axisLabel: { formatter: compactNumber }, splitLine: { lineStyle: { color: "#f5f5f4" } } },
	series: [["ຕົ້ນທຶນ", "known_cost"], ["ກຳໄລ", "gross_profit"], ["ບໍ່ຮູ້ຕົ້ນທຶນ", "unknown_cost_revenue"]].map(([name, key]) => ({ name, type: "bar", stack: "total", barMaxWidth: 26, data: report.value?.dashboard.sales_series.map((item: any) => item[key]) || [] })),
}));
const paymentOption = computed<EChartsCoreOption>(() => ({ color: ["#10b981", "#3b82f6", "#8b5cf6", "#f59e0b", "#a8a29e"], tooltip: { trigger: "item", formatter: (item: any) => `${item.name}<br/>${money(item.value)} · ${item.percent}%` }, legend: { bottom: 0, type: "scroll" }, series: [{ type: "pie", radius: ["48%", "72%"], center: ["50%", "43%"], padAngle: 2, itemStyle: { borderRadius: 5, borderColor: "#fff", borderWidth: 2 }, label: { show: false }, data: report.value?.dashboard.payment_mix.map((item: any) => ({ name: item.method, value: item.amount })) || [] }] }));
const stockMovementOption = computed<EChartsCoreOption>(() => ({ color: ["#10b981", "#3b82f6", "#f59e0b"], tooltip: { trigger: "axis" }, legend: { bottom: 0 }, grid: { left: 10, right: 16, top: 24, bottom: 48, containLabel: true }, xAxis: { type: "category", data: report.value?.stock.movement_series.map((item: any) => item.label) || [] }, yAxis: { type: "value", minInterval: 1, splitLine: { lineStyle: { color: "#f5f5f4" } } }, series: [{ name: "ຮັບເຂົ້າ", type: "bar", barMaxWidth: 22, data: report.value?.stock.movement_series.map((item: any) => item.in_qty) || [] }, { name: "ຂາຍອອກ", type: "bar", stack: "out", barMaxWidth: 22, data: report.value?.stock.movement_series.map((item: any) => item.sold_qty) || [] }, { name: "ປັບອອກ", type: "bar", stack: "out", barMaxWidth: 22, data: report.value?.stock.movement_series.map((item: any) => item.out_qty) || [] }] }));
const purchasingOption = computed<EChartsCoreOption>(() => ({ color: ["#6366f1"], tooltip: commonTooltip, grid: { left: 10, right: 10, top: 24, bottom: 32, containLabel: true }, xAxis: { type: "category", data: report.value?.purchasing.spend_series.map((item: any) => item.label) || [] }, yAxis: { type: "value", axisLabel: { formatter: compactNumber }, splitLine: { lineStyle: { color: "#f5f5f4" } } }, series: [{ name: "ຍອດຈັດຊື້", type: "line", smooth: true, symbol: "circle", symbolSize: 7, areaStyle: { color: "rgba(99,102,241,.14)" }, data: report.value?.purchasing.spend_series.map((item: any) => item.total_spend) || [] }] }));
const productOption = computed<EChartsCoreOption>(() => { const rows = [...(report.value?.dashboard.top_products || [])].slice(0, 8).reverse(); return { color: ["#10b981"], tooltip: commonTooltip, grid: { left: 8, right: 24, top: 8, bottom: 20, containLabel: true }, xAxis: { type: "value", axisLabel: { formatter: compactNumber }, splitLine: { lineStyle: { color: "#f5f5f4" } } }, yAxis: { type: "category", data: rows.map((item: any) => item.name), axisLabel: { width: 110, overflow: "truncate" } }, series: [{ type: "bar", barMaxWidth: 18, itemStyle: { borderRadius: [0, 5, 5, 0] }, data: rows.map((item: any) => item.revenue) }] }; });
const promotionValueOption = computed<EChartsCoreOption>(() => { const rows = report.value?.dashboard.promotion_performance || []; return { color: ["#f59e0b", "#8b5cf6"], tooltip: commonTooltip, legend: { bottom: 0 }, grid: { left: 10, right: 16, top: 24, bottom: 52, containLabel: true }, xAxis: { type: "category", data: rows.map((item: any) => item.promotion_name), axisLabel: { width: 110, overflow: "truncate" } }, yAxis: { type: "value", axisLabel: { formatter: compactNumber }, splitLine: { lineStyle: { color: "#f5f5f4" } } }, series: [{ name: "ສ່ວນຫຼຸດ", type: "bar", barMaxWidth: 24, data: rows.map((item: any) => item.discount_amount) }, { name: "ຕົ້ນທຶນຂອງແຖມ", type: "bar", barMaxWidth: 24, data: rows.map((item: any) => item.gift_cost) }] }; });
const promotionUsageOption = computed<EChartsCoreOption>(() => { const rows = report.value?.dashboard.promotion_performance || []; return { color: ["#10b981", "#3b82f6"], tooltip: { trigger: "axis" }, legend: { bottom: 0 }, grid: { left: 10, right: 16, top: 24, bottom: 52, containLabel: true }, xAxis: { type: "category", data: rows.map((item: any) => item.promotion_name), axisLabel: { width: 110, overflow: "truncate" } }, yAxis: { type: "value", minInterval: 1, splitLine: { lineStyle: { color: "#f5f5f4" } } }, series: [{ name: "ບິນ", type: "bar", barMaxWidth: 24, data: rows.map((item: any) => item.bill_count) }, { name: "ນຳໃຊ້", type: "bar", barMaxWidth: 24, data: rows.map((item: any) => item.applications) }] }; });
const heatmapOption = computed<EChartsCoreOption>(() => { const values = report.value?.dashboard.heatmap.map((item: any) => [item.hour, item.weekday, item.revenue]) || []; const maximum = Math.max(1, ...values.map((value: any) => Number(value[2]))); const weekdays = ["ຈັນ", "ອັງຄານ", "ພຸດ", "ພະຫັດ", "ສຸກ", "ເສົາ", "ອາທິດ"]; return { tooltip: { formatter: (item: any) => `${weekdays[item.value[1]]} ${String(item.value[0]).padStart(2, "0")}:00<br/>${money(item.value[2])}` }, grid: { left: 12, right: 20, top: 10, bottom: 42, containLabel: true }, xAxis: { type: "category", data: Array.from({ length: 24 }, (_, index) => String(index).padStart(2, "0")), splitArea: { show: true } }, yAxis: { type: "category", data: weekdays, splitArea: { show: true } }, visualMap: { min: 0, max: maximum, calculable: false, orient: "horizontal", left: "center", bottom: 0, inRange: { color: ["#ecfdf5", "#6ee7b7", "#059669"] } }, series: [{ type: "heatmap", data: values, itemStyle: { borderColor: "#fff", borderWidth: 2 } }] }; });
function periodText() { const p = report.value?.dashboard?.period; if (!p) return ""; const f = (value: string) => formatAppDateTime(value, "lo"); return `${f(p.from)} – ${f(new Date(new Date(p.to).getTime() - 1).toISOString())}`; }
function query() { const p = new URLSearchParams({ preset: preset.value, timezone_offset: "420" }); if (preset.value === "custom") { p.set("date_from", dateFrom.value); p.set("date_to", dateTo.value); } return p.toString(); }
async function load(options?: { refresh?: boolean }) { if (preset.value === "custom" && (!dateFrom.value || !dateTo.value)) return; if (options?.refresh) refreshing.value = true; else loading.value = true; error.value = ""; try { report.value = (await apiFetch<{ data: Detail }>(`/system-admin/reports/${encodeURIComponent(String(route.params.storeId))}?${query()}`)).data; } catch (cause) { error.value = resolveApiErrorMessage(cause, "ໂຫຼດລາຍງານຮ້ານບໍ່ສຳເລັດ"); } finally { loading.value = false; refreshing.value = false; } }
function selectPreset(id: string) { preset.value = id; if (id !== "custom") void load(); }
onMounted(() => void load());
</script>

<template>
	<AppSidebarShell :nav-items="appNavItems" :active-ids="['system-reports']" sidebar-eyebrow="ລະບົບ" sidebar-title="ຜູ້ດູແລລະບົບ" sidebar-compact-title="SYS" sidebar-description="ລາຍງານຂ້າມຮ້ານສຳລັບຜູ້ດູແລລະບົບ">
		<template #default="{ openSidebar }"><div class="min-w-0 space-y-3 pb-6">
			<AppPageHeader :title="report?.store.name || 'ລາຍງານຮ້ານ'" description="ລາຍງານສະເພາະຮ້ານນີ້ ຈາກພື້ນທີ່ System Admin" :title-badge="false" compact body-class="px-3 py-2.5 sm:px-4 sm:py-3" :tablet-layout="true" @menu="openSidebar"><template #actions><NuxtLink to="/system-admin/reports"><AppButton color="neutral" variant="soft" icon="i-heroicons-arrow-left-20-solid">ກັບໄປລາຍຊື່ຮ້ານ</AppButton></NuxtLink><AppButton color="neutral" variant="soft" icon="i-heroicons-arrow-path-20-solid" :loading="refreshing" @click="load({ refresh: true })">ໂຫຼດໃໝ່</AppButton></template></AppPageHeader>
			<section class="rounded-md border border-neutral-200 bg-white p-4 shadow-sm">
				<div class="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
					<div class="min-w-0">
						<h2 class="text-base font-semibold text-stone-950">ຊ່ວງລາຍງານ</h2>
						<p v-if="report" class="mt-1 text-sm text-stone-500">{{ periodText() }}</p>
						<p class="mt-1 text-xs text-stone-400">ຮອບວັນເລີ່ມ {{ report ? `${String(Math.floor(report.store.business_day_start_minutes / 60)).padStart(2, '0')}:${String(report.store.business_day_start_minutes % 60).padStart(2, '0')}` : '—' }}</p>
					</div>
					<div class="flex max-w-full flex-wrap gap-2 xl:max-w-[44rem] xl:justify-end">
						<AppButton v-for="item in presets" :key="item.id" size="sm" :color="preset === item.id ? 'primary' : 'neutral'" :variant="preset === item.id ? 'solid' : 'soft'" @click="selectPreset(item.id)">{{ item.label }}</AppButton>
					</div>
				</div>
				<div v-if="preset === 'custom'" class="mt-4 flex flex-col gap-3 border-t border-neutral-100 pt-4 lg:flex-row lg:items-end lg:justify-end">
					<AppDateRangePicker v-model:from="dateFrom" v-model:to="dateTo" :from-label="'ຈາກວັນທີ'" :to-label="'ເຖິງວັນທີ'" :select-label="'ເລືອກວັນທີ'" />
					<AppButton color="primary" class="lg:mb-0" @click="load()">ນຳໃຊ້</AppButton>
				</div>
			</section>
			<div v-if="loading" class="min-h-[320px] rounded-md border border-neutral-200 bg-white"><AppInlineLoadingBar container-class="bg-neutral-100" /></div><div v-else-if="error" class="rounded-md border border-rose-200 bg-rose-50 p-5 text-center text-sm text-rose-700">{{ error }}</div>
			<template v-else-if="report"><div class="flex gap-1 overflow-x-auto rounded-md border border-neutral-200 bg-white p-1.5 shadow-sm"><AppButton v-for="tab in tabs" :key="tab.id" size="sm" :variant="activeTab === tab.id ? 'solid' : 'ghost'" @click="activeTab = tab.id">{{ tab.label }}</AppButton></div>
				<div v-if="activeTab === 'sales'" class="space-y-3"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><UCard v-for="item in [{label:'ຍອດຂາຍສຸດທິ',value:money(report.dashboard.summary.revenue)},{label:'ຕົ້ນທຶນທີ່ຮູ້',value:money(report.dashboard.profitability.known_cost)},{label:'ກຳໄລຂັ້ນຕົ້ນ',value:money(report.dashboard.summary.gross_profit)},{label:'ຈຳນວນບິນ',value:number(report.dashboard.summary.bill_count)}]" :key="item.label"><p class="text-xs text-stone-500">{{ item.label }}</p><p class="mt-2 text-xl font-semibold text-stone-950">{{ item.value }}</p></UCard></div><UCard><div class="flex items-start justify-between gap-3"><div><h2 class="font-semibold">ຂໍ້ມູນຕົ້ນທຶນ</h2><p class="mt-1 text-sm text-stone-500">ກຳໄລຈະເຊື່ອຖືໄດ້ຕາມຄວາມຄົບຂອງຕົ້ນທຶນ</p></div><span class="text-lg font-semibold text-emerald-700">{{ report.dashboard.profitability.cost_coverage_percent.toFixed(1) }}%</span></div><div class="mt-4 grid gap-3 sm:grid-cols-3"><div><p class="text-xs text-stone-500">ຍອດຂາຍບໍ່ມີຕົ້ນທຶນ</p><p class="mt-1 font-semibold">{{ money(report.dashboard.profitability.unknown_cost_revenue) }}</p></div><div><p class="text-xs text-stone-500">ສ່ວນຫຼຸດ</p><p class="mt-1 font-semibold">{{ money(report.dashboard.summary.discount) }}</p></div><div><p class="text-xs text-stone-500">VAT</p><p class="mt-1 font-semibold">{{ money(report.dashboard.summary.vat_amount) }}</p></div></div></UCard></div>
				<div v-else-if="activeTab === 'stock'" class="space-y-3"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><UCard v-for="item in [{label:'ມູນຄ່າສະຕັອກ',value:money(report.stock.summary.inventory_value)},{label:'ສະຕັອກຕ່ຳ',value:number(report.stock.summary.low_count)},{label:'ສິນຄ້າໝົດ',value:number(report.stock.summary.out_count)},{label:'ສະຕັອກຕິດລົບ',value:number(report.stock.summary.negative_count)}]" :key="item.label"><p class="text-xs text-stone-500">{{ item.label }}</p><p class="mt-2 text-xl font-semibold text-stone-950">{{ item.value }}</p></UCard></div><div class="grid gap-3 xl:grid-cols-2"><UCard><h2 class="font-semibold">ສິນຄ້າທີ່ຄວນກວດ</h2><div class="mt-4 divide-y divide-neutral-100"><div v-for="item in report.stock.low_stock" :key="item.id" class="flex items-center justify-between py-3"><div><p class="font-medium">{{ item.name }}</p><p class="text-xs text-stone-500">{{ item.sku }}</p></div><p class="text-sm">{{ number(item.available_base) }} / {{ number(item.threshold) }}</p></div><p v-if="!report.stock.low_stock.length" class="py-6 text-center text-sm text-emerald-700">ບໍ່ພົບສິນຄ້າທີ່ຕ້ອງເພີ່ມສະຕັອກ</p></div></UCard><UCard><h2 class="font-semibold">ມູນຄ່າສະຕັອກສູງສຸດ</h2><div class="mt-3 divide-y divide-neutral-100"><div v-for="item in report.stock.top_products" :key="item.id" class="flex items-center justify-between gap-3 py-2"><div class="min-w-0"><p class="truncate font-medium">{{ item.name }}</p><p class="text-xs text-stone-400">{{ item.sku }} · {{ number(item.on_hand_base) }} ຄົງເຫຼືອ</p></div><span class="shrink-0 font-medium">{{ money(item.value) }}</span></div></div></UCard></div><UCard><h2 class="font-semibold">ການເຄື່ອນໄຫວສະຕັອກໃນຊ່ວງນີ້</h2><div class="mt-3 overflow-x-auto"><table class="min-w-[600px] w-full text-sm"><thead class="border-b text-left text-xs text-stone-500"><tr><th class="pb-2">ໄລຍະເວລາ</th><th class="pb-2 text-right">ຮັບເຂົ້າ</th><th class="pb-2 text-right">ຂາຍອອກ</th><th class="pb-2 text-right">ປັບອອກ</th></tr></thead><tbody><tr v-for="item in report.stock.movement_series" :key="item.label" class="border-b border-neutral-100"><td class="py-2">{{ item.label }}</td><td class="py-2 text-right text-emerald-700">+{{ number(item.in_qty) }}</td><td class="py-2 text-right">−{{ number(item.sold_qty) }}</td><td class="py-2 text-right text-amber-700">−{{ number(item.out_qty) }}</td></tr></tbody></table></div></UCard></div>
				<div v-else-if="activeTab === 'purchasing'" class="space-y-3"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><UCard v-for="item in [{label:'ຍອດຮັບສິນຄ້າ',value:money(report.purchasing.summary.total_spend)},{label:'ຄ່າສິນຄ້າ',value:money(report.purchasing.summary.goods_cost)},{label:'ຄ່າຂົນສົ່ງ/ອື່ນໆ',value:money(report.purchasing.summary.shipping_cost + report.purchasing.summary.other_cost)},{label:'ໃບສັ່ງຊື້ທີ່ຮັບແລ້ວ',value:number(report.purchasing.summary.po_count)}]" :key="item.label"><p class="text-xs text-stone-500">{{ item.label }}</p><p class="mt-2 text-xl font-semibold text-stone-950">{{ item.value }}</p></UCard></div><div class="grid gap-3 xl:grid-cols-2"><UCard><h2 class="font-semibold">ໜີ້ຄ່າສິນຄ້າທີ່ຄ້າງຈ່າຍ</h2><p class="mt-2 text-2xl font-semibold">{{ money(report.purchasing.payable.amount) }}</p><p class="mt-1 text-xs text-stone-500">{{ number(report.purchasing.payable.po_count) }} ໃບສັ່ງຊື້</p></UCard><UCard><h2 class="font-semibold">ສິນຄ້າທີ່ລໍຖ້າຮັບ</h2><p class="mt-2 text-2xl font-semibold">{{ number(report.purchasing.outstanding.qty) }}</p><p class="mt-1 text-xs text-stone-500">{{ number(report.purchasing.outstanding.po_count) }} ໃບ · {{ money(report.purchasing.outstanding.amount) }}</p></UCard></div><UCard><h2 class="font-semibold">ຜູ້ສະໜອງ</h2><div class="mt-3 overflow-x-auto"><table class="min-w-[520px] w-full text-sm"><thead class="border-b text-left text-xs text-stone-500"><tr><th class="pb-2">ຜູ້ສະໜອງ</th><th class="pb-2 text-right">ໃບສັ່ງຊື້</th><th class="pb-2 text-right">ມູນຄ່າຮັບສິນຄ້າ</th></tr></thead><tbody><tr v-for="item in report.purchasing.suppliers" :key="item.supplier_name" class="border-b border-neutral-100"><td class="py-2">{{ item.supplier_name || 'ບໍ່ໄດ້ລະບຸ' }}</td><td class="py-2 text-right">{{ number(item.po_count) }}</td><td class="py-2 text-right font-medium">{{ money(item.total_spend) }}</td></tr></tbody></table></div></UCard><UCard><h2 class="font-semibold">ສິນຄ້າຮັບເຂົ້າ</h2><div class="mt-3 overflow-x-auto"><table class="min-w-[720px] w-full text-sm"><thead class="border-b text-left text-xs text-stone-500"><tr><th class="pb-2">ສິນຄ້າ</th><th class="pb-2 text-right">ຮັບແລ້ວ</th><th class="pb-2 text-right">ຍັງຄ້າງ</th><th class="pb-2 text-right">ຕົ້ນທຶນຮັບເຂົ້າ</th></tr></thead><tbody><tr v-for="item in report.purchasing.products" :key="item.id" class="border-b border-neutral-100"><td class="py-2"><p class="font-medium">{{ item.name }}</p><p class="text-xs text-stone-400">{{ item.sku }}</p></td><td class="py-2 text-right">{{ number(item.qty_received) }}</td><td class="py-2 text-right">{{ number(item.qty_outstanding) }}</td><td class="py-2 text-right font-medium">{{ money(item.total_cost) }}</td></tr></tbody></table></div></UCard></div>
				<div v-else-if="activeTab === 'products'" class="space-y-3"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><UCard v-for="item in [{label:'ສິນຄ້າຂາຍໄດ້',value:number(report.products.totals.product_count)},{label:'ຈຳນວນຂາຍ',value:number(report.products.totals.quantity)},{label:'ລາຍຮັບສິນຄ້າ',value:money(report.products.totals.revenue)},{label:'ປະເພດສິນຄ້າ',value:number(report.dashboard.category_performance.length)}]" :key="item.label"><p class="text-xs text-stone-500">{{ item.label }}</p><p class="mt-2 text-xl font-semibold text-stone-950">{{ item.value }}</p></UCard></div><UCard><h2 class="font-semibold">ຜົນງານສິນຄ້າ</h2><div class="mt-3 overflow-x-auto"><table class="min-w-[900px] w-full text-sm"><thead class="border-b text-left text-xs text-stone-500"><tr><th class="pb-2">ສິນຄ້າ</th><th class="pb-2 text-right">ຈຳນວນ</th><th class="pb-2 text-right">ລາຍຮັບ</th><th class="pb-2 text-right">ຕົ້ນທຶນ</th><th class="pb-2 text-right">ກຳໄລ</th><th class="pb-2 text-right">Margin</th></tr></thead><tbody><tr v-for="item in report.products.items" :key="item.id" class="border-b border-neutral-100"><td class="py-2"><p class="font-medium">{{ item.name }}</p><p class="text-xs text-stone-400">{{ item.sku }}</p></td><td class="py-2 text-right">{{ number(item.quantity) }}</td><td class="py-2 text-right">{{ money(item.revenue) }}</td><td class="py-2 text-right">{{ money(item.known_cost) }}</td><td class="py-2 text-right font-medium text-emerald-700">{{ money(item.gross_profit) }}</td><td class="py-2 text-right">{{ item.margin.toFixed(1) }}%</td></tr></tbody></table></div></UCard><UCard><h2 class="font-semibold">ຍອດຂາຍຕາມໝວດໝູ່</h2><div class="mt-3 overflow-x-auto"><table class="min-w-[680px] w-full text-sm"><thead class="border-b text-left text-xs text-stone-500"><tr><th class="pb-2">ໝວດໝູ່</th><th class="pb-2 text-right">ຈຳນວນ</th><th class="pb-2 text-right">ລາຍຮັບ</th><th class="pb-2 text-right">ກຳໄລ</th><th class="pb-2 text-right">ຕົ້ນທຶນຄົບ</th></tr></thead><tbody><tr v-for="item in report.dashboard.category_performance" :key="item.id" class="border-b border-neutral-100"><td class="py-2 font-medium">{{ item.name }}</td><td class="py-2 text-right">{{ number(item.quantity) }}</td><td class="py-2 text-right">{{ money(item.revenue) }}</td><td class="py-2 text-right text-emerald-700">{{ money(item.gross_profit) }}</td><td class="py-2 text-right">{{ item.cost_coverage_percent.toFixed(0) }}%</td></tr></tbody></table></div></UCard></div>
				<div v-else-if="activeTab === 'promotions'" class="space-y-3"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><UCard v-for="item in [{label:'ບິນທີ່ໃຊ້ໂປຣໂມຊັນ',value:number(report.dashboard.promotion_summary.promotion_bill_count)},{label:'ຈຳນວນນຳໃຊ້',value:number(report.dashboard.promotion_summary.applications)},{label:'ສ່ວນຫຼຸດ',value:money(report.dashboard.promotion_summary.discount_amount)},{label:'ຂອງແຖມ',value:number(report.dashboard.promotion_summary.gift_quantity)}]" :key="item.label"><p class="text-xs text-stone-500">{{ item.label }}</p><p class="mt-2 text-xl font-semibold text-stone-950">{{ item.value }}</p></UCard></div><UCard><h2 class="font-semibold">ຜົນງານໂປຣໂມຊັນ</h2><div class="mt-3 overflow-x-auto"><table class="min-w-[760px] w-full text-sm"><thead class="border-b text-left text-xs text-stone-500"><tr><th class="pb-2">ໂປຣໂມຊັນ</th><th class="pb-2 text-right">ບິນ</th><th class="pb-2 text-right">ນຳໃຊ້</th><th class="pb-2 text-right">ສ່ວນຫຼຸດ</th><th class="pb-2 text-right">ຂອງແຖມ</th><th class="pb-2 text-right">ຕົ້ນທຶນແຖມ</th></tr></thead><tbody><tr v-for="item in report.dashboard.promotion_performance" :key="item.promotion_id" class="border-b border-neutral-100"><td class="py-2 font-medium">{{ item.promotion_name }}</td><td class="py-2 text-right">{{ number(item.bill_count) }}</td><td class="py-2 text-right">{{ number(item.applications) }}</td><td class="py-2 text-right">{{ money(item.discount_amount) }}</td><td class="py-2 text-right">{{ number(item.gift_quantity) }}</td><td class="py-2 text-right">{{ money(item.gift_cost) }}</td></tr></tbody></table></div><p v-if="!report.dashboard.promotion_performance.length" class="py-8 text-center text-sm text-stone-500">ບໍ່ມີການໃຊ້ໂປຣໂມຊັນໃນຊ່ວງນີ້</p></UCard></div>
				<div v-else class="space-y-3"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><UCard v-for="item in [{label:'ບິນຍົກເລີກ/ຄືນເງິນ',value:number(report.dashboard.summary.cancelled_refunded_count)},{label:'ສິນຄ້າຄວນເພີ່ມສະຕັອກ',value:number(report.dashboard.operational_signals.restock_sku_count)},{label:'ສິນຄ້າບໍ່ມີຍອດຂາຍ',value:number(report.dashboard.operational_signals.no_sales_count)},{label:'ຊ່ວງຂາຍສູງ',value:report.dashboard.operational_signals.peak_period || '—'}]" :key="item.label"><p class="text-xs text-stone-500">{{ item.label }}</p><p class="mt-2 text-xl font-semibold text-stone-950">{{ item.value }}</p></UCard></div><div class="grid gap-3 xl:grid-cols-2"><UCard><h2 class="font-semibold">ວິທີຮັບຊຳລະ</h2><div class="mt-3 divide-y divide-neutral-100"><div v-for="item in report.dashboard.payment_mix" :key="item.method" class="flex items-center justify-between py-2"><span>{{ item.method }}</span><span class="font-medium">{{ money(item.amount) }} · {{ item.percent.toFixed(1) }}%</span></div></div></UCard><UCard><h2 class="font-semibold">ພະນັກງານຂາຍ</h2><div class="mt-3 divide-y divide-neutral-100"><div v-for="item in report.dashboard.staff_ranking" :key="item.id" class="flex items-center justify-between py-2"><span>{{ item.name }}</span><span class="font-medium">{{ number(item.bill_count) }} ບິນ · {{ money(item.revenue) }}</span></div></div></UCard></div><UCard><h2 class="font-semibold">ແນວໂນ້ມຍອດຂາຍ</h2><div class="mt-3 overflow-x-auto"><table class="min-w-[620px] w-full text-sm"><thead class="border-b text-left text-xs text-stone-500"><tr><th class="pb-2">ໄລຍະເວລາ</th><th class="pb-2 text-right">ຍອດຂາຍ</th><th class="pb-2 text-right">ບິນ</th><th class="pb-2 text-right">ຕົ້ນທຶນທີ່ຮູ້</th><th class="pb-2 text-right">ກຳໄລ</th></tr></thead><tbody><tr v-for="item in report.dashboard.sales_series" :key="item.label" class="border-b border-neutral-100"><td class="py-2">{{ item.label }}</td><td class="py-2 text-right">{{ money(item.revenue) }}</td><td class="py-2 text-right">{{ number(item.bill_count) }}</td><td class="py-2 text-right">{{ money(item.known_cost) }}</td><td class="py-2 text-right font-medium text-emerald-700">{{ money(item.gross_profit) }}</td></tr></tbody></table></div></UCard></div>
			</template>
			<div v-if="report && activeTab === 'sales'" class="mt-3 grid gap-3 xl:grid-cols-3">
				<UCard class="xl:col-span-2"><h2 class="font-semibold">ແນວໂນ້ມຍອດຂາຍ</h2><ReportsReportChart :option="salesOption" :empty="!report.dashboard.sales_series.length" /></UCard>
				<UCard><h2 class="font-semibold">ສັດສ່ວນການຊຳລະ</h2><ReportsReportChart :option="paymentOption" :empty="!report.dashboard.payment_mix.length" /></UCard>
				<UCard class="xl:col-span-3"><h2 class="font-semibold">ລາຍຮັບ ຕົ້ນທຶນ ແລະ ກຳໄລ</h2><ReportsReportChart :option="profitOption" :empty="!report.dashboard.sales_series.length" /></UCard>
			</div>
			<UCard v-if="report && activeTab === 'stock'" class="mt-3"><h2 class="font-semibold">ການເຄື່ອນໄຫວສະຕັອກ</h2><ReportsReportChart :option="stockMovementOption" :empty="!report.stock.movement_series.length" /></UCard>
			<UCard v-if="report && activeTab === 'purchasing'" class="mt-3"><h2 class="font-semibold">ແນວໂນ້ມການຈັດຊື້</h2><ReportsReportChart :option="purchasingOption" :empty="!report.purchasing.spend_series.length" /></UCard>
			<UCard v-if="report && activeTab === 'products'" class="mt-3"><h2 class="font-semibold">ສິນຄ້າຂາຍດີ</h2><ReportsReportChart :option="productOption" :empty="!report.dashboard.top_products.length" /></UCard>
			<div v-if="report && activeTab === 'promotions'" class="mt-3 grid gap-3 xl:grid-cols-2"><UCard><h2 class="font-semibold">ສ່ວນຫຼຸດ ແລະ ຕົ້ນທຶນຂອງແຖມ</h2><ReportsReportChart :option="promotionValueOption" :empty="!report.dashboard.promotion_performance.length" /></UCard><UCard><h2 class="font-semibold">ຈຳນວນບິນ ແລະ ການນຳໃຊ້</h2><ReportsReportChart :option="promotionUsageOption" :empty="!report.dashboard.promotion_performance.length" /></UCard></div>
			<UCard v-if="report && activeTab === 'operations'" class="mt-3"><h2 class="font-semibold">ຊ່ວງເວລາຂາຍ</h2><p class="mt-1 text-xs text-stone-500">ເບິ່ງຍອດຂາຍແຍກຕາມມື້ ແລະ ຊົ່ວໂມງ</p><ReportsReportChart :option="heatmapOption" height="360px" :empty="!report.dashboard.heatmap.length" /></UCard>
		</div></template>
	</AppSidebarShell>
</template>
