<script setup lang="ts">
import type { EChartsCoreOption } from "echarts/core";
import { formatMoneyWithSymbol } from "~/utils/currency";
import { appNavItems } from "~/utils/app-nav";

type Comparison={value:number|null;available:boolean};type Preset="today"|"yesterday"|"this_week"|"last_week"|"this_month"|"last_month"|"custom";
type Dashboard={currency:string;generated_at:string;period:{date_from:string;date_to:string;days:number};summary:{revenue:number;bill_count:number;average_bill:number;cancelled_refunded_count:number;gross_profit:number;gross_margin_percent:number;comparison:Record<string,Comparison>};profitability:{known_cost:number;known_gross_profit:number;gross_margin_percent:number;unknown_cost_revenue:number;unknown_cost_bills:number};sales_series:Array<{label:string;revenue:number;bill_count:number;known_cost:number;gross_profit:number;unknown_cost_revenue:number}>;payment_mix:Array<{method:string;amount:number;bill_count:number;percent:number}>;top_products:Array<{id:string;name:string;sku:string;quantity:number;revenue:number;comparison:Comparison}>;order_type_mix:Array<{type:string;revenue:number;bill_count:number}>;order_type_series:Array<{label:string;type:string;revenue:number;bill_count:number}>;heatmap:Array<{weekday:number;hour:number;revenue:number;bill_count:number}>;staff_ranking:Array<{id:string;name:string;bill_count:number;revenue:number;average_bill:number}>;low_stock:Array<{id:string;name:string;sku:string;available_base:number;threshold:number}>;operational_signals:{peak_period:string|null;peak_revenue:number;primary_payment_method:string|null;primary_payment_percent:number;restock_sku_count:number}};
type ProductRow={id:string;name:string;sku:string;category_name:string;quantity:number;average_price:number;revenue:number;known_cost:number;gross_profit:number;margin:number;bill_count:number;comparison:Comparison};
type ProductReport={items:ProductRow[];categories:Array<{id:string;name:string}>;pagination:{page:number;limit:number;total:number;pages:number}};
const {apiFetch}=useApiClient(),{currentStoreId}=useAuthSession(),{locale}=useI18n();
const activePreset=ref<Preset>("today"),activeView=ref<"sales"|"products"|"operations">("sales"),dateFrom=ref(""),dateTo=ref("");const dashboard=ref<Dashboard|null>(null),loading=ref(false),errorMessage=ref(""),version=ref(0);
const productMetric=ref<"revenue"|"quantity">("revenue"),heatMetric=ref<"revenue"|"bill_count">("revenue"),productReport=ref<ProductReport|null>(null),productLoading=ref(false),productSearch=ref(""),productCategory=ref(""),productSort=ref("revenue"),productOrder=ref<"asc"|"desc">("desc"),productPage=ref(1),selectedProduct=ref<ProductRow|null>(null),productTrend=ref<Array<{label:string;quantity:number;revenue:number}>>([]),trendLoading=ref(false);
const intlLocale=computed(()=>locale.value==="lo"?"lo-LA":locale.value==="en"?"en-US":"th-TH"),money=(value:number)=>formatMoneyWithSymbol(value,dashboard.value?.currency||"LAK",{locale:intlLocale.value,maximumFractionDigits:0}),num=(value:number)=>new Intl.NumberFormat(intlLocale.value,{maximumFractionDigits:2}).format(value);
const presets=[{id:"today",label:"ມື້ນີ້"},{id:"yesterday",label:"ມື້ວານ"},{id:"this_week",label:"ອາທິດນີ້"},{id:"last_week",label:"ອາທິດກ່ອນ"},{id:"this_month",label:"ເດືອນນີ້"},{id:"last_month",label:"ເດືອນກ່ອນ"},{id:"custom",label:"ກຳນົດເອງ"}] as const;
const paymentLabel=(method:string|null)=>!method?"-":method==="cash"?"ເງິນສົດ":["qr","qr_transfer","transfer","bank_transfer"].includes(method)?"QR / ໂອນ":["card","credit_card"].includes(method)?"ບັດເຄຣດິດ":method;
const orderTypeLabel=(type:string)=>["restaurant","dine_in","table"].includes(type)?"ກິນຢູ່ຮ້ານ":["quick_sale","counter","pos"].includes(type)?"ຂາຍດ່ວນ":type==="other"?"ອື່ນໆ":type;
function query(){const params=new URLSearchParams({store_id:currentStoreId.value||"",preset:activePreset.value,timezone_offset:String(-new Date().getTimezoneOffset())});if(activePreset.value==="custom"){params.set("date_from",dateFrom.value);params.set("date_to",dateTo.value);}return params;}
async function loadDashboard(){if(!currentStoreId.value)return;if(activePreset.value==="custom"&&(!dateFrom.value||!dateTo.value))return;const token=++version.value;loading.value=true;errorMessage.value="";try{const response=await apiFetch<{data:Dashboard}>(`/reports/dashboard?${query()}`);if(token===version.value)dashboard.value=response.data;}catch(error:any){if(token===version.value)errorMessage.value=String(error?.data?.message||error?.message||"Unable to load reports");}finally{if(token===version.value)loading.value=false;}}
async function loadProducts(){if(!currentStoreId.value||activeView.value!=="products")return;productLoading.value=true;try{const params=query();if(productSearch.value)params.set("search",productSearch.value);if(productCategory.value)params.set("category_id",productCategory.value);params.set("sort",productSort.value);params.set("order",productOrder.value);params.set("page",String(productPage.value));params.set("limit","20");productReport.value=(await apiFetch<{data:ProductReport}>(`/reports/products?${params}`)).data;}finally{productLoading.value=false;}}
let searchTimer:ReturnType<typeof setTimeout>|undefined;watch([activePreset,dateFrom,dateTo,currentStoreId],()=>void loadDashboard(),{immediate:true});watch([activePreset,dateFrom,dateTo,currentStoreId,activeView,productCategory,productSort,productOrder,productPage],()=>void loadProducts());watch(productSearch,()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{productPage.value=1;void loadProducts();},300);});
async function openProduct(item:ProductRow){selectedProduct.value=item;trendLoading.value=true;try{productTrend.value=(await apiFetch<{data:{items:typeof productTrend.value}}>(`/reports/products/${encodeURIComponent(item.id)}/trend?${query()}`)).data.items;}finally{trendLoading.value=false;}}
const periodText=computed(()=>dashboard.value?dashboard.value.period.date_from===dashboard.value.period.date_to?dashboard.value.period.date_from:`${dashboard.value.period.date_from} – ${dashboard.value.period.date_to}`:"-");
const metricCards=computed(()=>dashboard.value?[{label:"ຍອດຂາຍສຸດທິ",value:money(dashboard.value.summary.revenue),compare:dashboard.value.summary.comparison.revenue,tone:"emerald"},{label:"ຈຳນວນບິນ",value:num(dashboard.value.summary.bill_count),compare:dashboard.value.summary.comparison.bill_count,tone:"blue"},{label:"ບິນສະເລ່ຍ",value:money(dashboard.value.summary.average_bill),compare:dashboard.value.summary.comparison.average_bill,tone:"violet"},{label:"ຍົກເລີກ / ຄືນເງິນ",value:num(dashboard.value.summary.cancelled_refunded_count),compare:dashboard.value.summary.comparison.cancelled_refunded_count,tone:"rose"},{label:"ກຳໄລຂັ້ນຕົ້ນ",value:money(dashboard.value.summary.gross_profit),tone:"amber"},{label:"Margin",value:`${dashboard.value.summary.gross_margin_percent.toFixed(1)}%`,tone:"stone"}]:[]);
const comparisonText=(item?:Comparison)=>item?.available&&item.value!==null?`${item.value>=0?"+":""}${item.value.toFixed(1)}%`:"—";
const commonTooltip={trigger:"axis",backgroundColor:"#fff",borderColor:"#e7e5e4",textStyle:{color:"#292524"}};
const salesOption=computed<EChartsCoreOption>(()=>({color:["#10b981","#3b82f6"],tooltip:commonTooltip,legend:{bottom:0,data:["ຍອດຂາຍ","ຈຳນວນບິນ"]},grid:{left:12,right:18,top:24,bottom:54,containLabel:true},xAxis:{type:"category",data:dashboard.value?.sales_series.map(x=>x.label)||[],axisLine:{lineStyle:{color:"#d6d3d1"}}},yAxis:[{type:"value",axisLabel:{formatter:(v:number)=>Intl.NumberFormat("en",{notation:"compact"}).format(v)},splitLine:{lineStyle:{color:"#f5f5f4"}}},{type:"value",splitLine:{show:false}}],dataZoom:(dashboard.value?.sales_series.length||0)>14?[{type:"inside"},{type:"slider",height:14,bottom:28}]:[],series:[{name:"ຍອດຂາຍ",type:"line",smooth:true,symbol:"circle",symbolSize:7,areaStyle:{color:"rgba(16,185,129,.14)"},data:dashboard.value?.sales_series.map(x=>x.revenue)||[]},{name:"ຈຳນວນບິນ",type:"bar",yAxisIndex:1,barMaxWidth:18,itemStyle:{color:"rgba(59,130,246,.35)",borderRadius:[4,4,0,0]},data:dashboard.value?.sales_series.map(x=>x.bill_count)||[]}]}));
const profitOption=computed<EChartsCoreOption>(()=>({color:["#f59e0b","#10b981","#a8a29e"],tooltip:commonTooltip,legend:{bottom:0},grid:{left:10,right:10,top:24,bottom:48,containLabel:true},xAxis:{type:"category",data:dashboard.value?.sales_series.map(x=>x.label)||[]},yAxis:{type:"value",axisLabel:{formatter:(v:number)=>Intl.NumberFormat("en",{notation:"compact"}).format(v)},splitLine:{lineStyle:{color:"#f5f5f4"}}},series:[["ຕົ້ນທຶນ","known_cost"],["ກຳໄລ","gross_profit"],["ບໍ່ຮູ້ຕົ້ນທຶນ","unknown_cost_revenue"]].map(([name,key])=>({name,type:"bar",stack:"total",barMaxWidth:26,data:dashboard.value?.sales_series.map(x=>x[key as keyof typeof x])||[]}))}));
const donutOption=computed<EChartsCoreOption>(()=>({color:["#10b981","#3b82f6","#8b5cf6","#f59e0b","#a8a29e"],tooltip:{trigger:"item",formatter:(p:any)=>`${p.name}<br/>${money(p.value)} · ${p.percent}%`},legend:{bottom:0,type:"scroll"},series:[{type:"pie",radius:["48%","72%"],center:["50%","43%"],padAngle:2,itemStyle:{borderRadius:5,borderColor:"#fff",borderWidth:2},label:{show:false},data:dashboard.value?.payment_mix.map(x=>({name:paymentLabel(x.method),value:x.amount}))||[]}]}));
const productOption=computed<EChartsCoreOption>(()=>{const rows=[...(dashboard.value?.top_products||[])].slice(0,8).reverse();return{color:["#10b981"],tooltip:{trigger:"axis",axisPointer:{type:"shadow"}},grid:{left:8,right:24,top:8,bottom:20,containLabel:true},xAxis:{type:"value",splitLine:{lineStyle:{color:"#f5f5f4"}}},yAxis:{type:"category",data:rows.map(x=>x.name),axisLabel:{width:110,overflow:"truncate"}},series:[{type:"bar",barMaxWidth:18,itemStyle:{borderRadius:[0,5,5,0]},data:rows.map(x=>productMetric.value==="revenue"?x.revenue:x.quantity)}]};});
const orderOption=computed<EChartsCoreOption>(()=>{const labels=dashboard.value?.sales_series.map(x=>x.label)||[],types=[...new Set(dashboard.value?.order_type_series.map(x=>x.type)||[])];return{color:["#10b981","#3b82f6","#8b5cf6","#f59e0b"],tooltip:{trigger:"axis",axisPointer:{type:"shadow"}},legend:{bottom:0},grid:{left:8,right:16,top:28,bottom:48,containLabel:true},xAxis:{type:"category",data:labels},yAxis:{type:"value",splitLine:{lineStyle:{color:"#f5f5f4"}}},series:types.map(type=>({name:orderTypeLabel(type),type:"bar",stack:"orders",barMaxWidth:26,data:labels.map(label=>dashboard.value?.order_type_series.find(x=>x.label===label&&x.type===type)?.revenue||0)}))};});
const heatOption=computed<EChartsCoreOption>(()=>{const values=dashboard.value?.heatmap.map(x=>[x.hour,x.weekday,heatMetric.value==="revenue"?x.revenue:x.bill_count])||[],max=Math.max(1,...values.map(x=>Number(x[2])));return{tooltip:{formatter:(p:any)=>`${["ອາທິດ","ຈັນ","ອັງຄານ","ພຸດ","ພະຫັດ","ສຸກ","ເສົາ"][p.value[1]]} ${String(p.value[0]).padStart(2,"0")}:00<br/>${heatMetric.value==="revenue"?money(p.value[2]):`${p.value[2]} ບິນ`}`},grid:{left:12,right:20,top:10,bottom:42,containLabel:true},xAxis:{type:"category",data:Array.from({length:24},(_,i)=>String(i).padStart(2,"0")),splitArea:{show:true}},yAxis:{type:"category",data:["ອາທິດ","ຈັນ","ອັງຄານ","ພຸດ","ພະຫັດ","ສຸກ","ເສົາ"],splitArea:{show:true}},visualMap:{min:0,max,calculable:false,orient:"horizontal",left:"center",bottom:0,inRange:{color:["#ecfdf5","#6ee7b7","#059669"]}},series:[{type:"heatmap",data:values,itemStyle:{borderColor:"#fff",borderWidth:2}}]};});
const trendOption=computed<EChartsCoreOption>(()=>({color:["#10b981"],tooltip:commonTooltip,grid:{left:8,right:12,top:16,bottom:28,containLabel:true},xAxis:{type:"category",data:productTrend.value.map(x=>x.label)},yAxis:{type:"value",splitLine:{lineStyle:{color:"#f5f5f4"}}},series:[{type:"line",smooth:true,areaStyle:{color:"rgba(16,185,129,.14)"},data:productTrend.value.map(x=>x.revenue)}]}));
</script>

<template><AppSidebarShell :nav-items="appNavItems" :active-ids="['reports']" sidebar-eyebrow="Reports" sidebar-title="ລາຍງານ" sidebar-compact-title="REP" sidebar-description="ວິເຄາະຍອດຂາຍຈາກຂໍ້ມູນຈິງ"><template #default="{openSidebar}"><div class="grid min-w-0 gap-3 pb-4">
	<AppPageHeader :title-badge="false" compact title="" body-class="px-3 py-2.5 sm:px-4 sm:py-3" @menu="openSidebar"><div class="flex min-h-10 items-center justify-between gap-3"><div class="min-w-0"><div class="flex min-w-0 items-baseline gap-2"><h1 class="shrink-0 text-base font-semibold tracking-[-0.02em] text-stone-950">ລາຍງານ</h1><span class="truncate text-sm font-medium text-stone-600">{{periodText}}</span></div><p class="mt-0.5 text-xs text-stone-400">ອັບເດດ {{dashboard?.generated_at?new Date(dashboard.generated_at).toLocaleTimeString(intlLocale):'-'}}</p></div><AppButton icon="i-heroicons-arrow-path-20-solid" color="neutral" variant="soft" size="md" class="shrink-0 self-center rounded-md" label="ໂຫຼດໃໝ່" :loading="loading" :spin-icon-on-loading="true" @click="loadDashboard"/></div></AppPageHeader>
	<div class="rounded-md border border-stone-200 bg-white p-3 shadow-sm"><div class="flex gap-2 overflow-x-auto pb-1"><AppButton v-for="preset in presets" :key="preset.id" :color="activePreset===preset.id?'primary':'neutral'" :variant="activePreset===preset.id?'solid':'soft'" :label="preset.label" class="shrink-0" @click="activePreset=preset.id"/></div><div v-if="activePreset==='custom'" class="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input v-model="dateFrom" type="date" class="rounded-md border border-stone-300 px-3 py-2 text-sm"><input v-model="dateTo" type="date" class="rounded-md border border-stone-300 px-3 py-2 text-sm"><AppButton color="primary" label="ນຳໃຊ້" @click="loadDashboard"/></div></div>
	<div v-if="loading&&!dashboard" class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><USkeleton v-for="i in 6" :key="i" class="h-28 rounded-md"/></div><div v-else-if="errorMessage" class="rounded-md border border-rose-200 bg-rose-50 p-8 text-center"><p class="font-semibold text-rose-900">{{errorMessage}}</p><AppButton class="mt-4" label="ລອງໃໝ່" @click="loadDashboard"/></div>
	<template v-else-if="dashboard"><div class="grid grid-cols-2 gap-3 xl:grid-cols-6"><div v-for="card in metricCards" :key="card.label" class="rounded-md border border-stone-200 bg-white p-4 shadow-sm"><div class="flex items-start justify-between gap-2"><p class="text-xs font-semibold text-stone-500">{{card.label}}</p><span v-if="card.compare" class="rounded-full bg-stone-50 px-2 py-0.5 text-[10px]" :class="card.compare.value!==null&&card.compare.value>=0?'text-emerald-700':'text-rose-700'">{{comparisonText(card.compare)}}</span></div><p class="mt-2 truncate text-xl font-semibold text-stone-950 sm:text-2xl">{{card.value}}</p></div></div>
	<div class="flex gap-2 overflow-x-auto rounded-md border border-stone-200 bg-white p-2"><AppButton v-for="tab in [{id:'sales',label:'ຍອດຂາຍ'},{id:'products',label:'ສິນຄ້າ'},{id:'operations',label:'ການດຳເນີນງານ'}]" :key="tab.id" :color="activeView===tab.id?'primary':'neutral'" :variant="activeView===tab.id?'solid':'ghost'" :label="tab.label" @click="activeView=tab.id as any"/></div>
	<template v-if="activeView==='sales'"><div class="grid gap-3 xl:grid-cols-[1.4fr_.6fr]"><UCard><h2 class="font-semibold">ແນວໂນ້ມຍອດຂາຍ</h2><ReportsReportChart :option="salesOption" :empty="!dashboard.sales_series.some(x=>x.revenue)"/></UCard><UCard><h2 class="font-semibold">ສັດສ່ວນການຊຳລະ</h2><ReportsReportChart :option="donutOption" :empty="!dashboard.payment_mix.length"/></UCard></div><div class="grid gap-3 xl:grid-cols-2"><UCard><div class="flex justify-between"><h2 class="font-semibold">ລາຍຮັບ ຕົ້ນທຶນ ແລະ ກຳໄລ</h2><span v-if="dashboard.profitability.unknown_cost_bills" class="text-xs text-amber-700" :title="`${dashboard.profitability.unknown_cost_bills} ບິນມີຕົ້ນທຶນບໍ່ຄົບ`">⚠ ຕົ້ນທຶນບໍ່ຄົບ</span></div><ReportsReportChart :option="profitOption" :empty="!dashboard.sales_series.some(x=>x.revenue)"/></UCard><UCard><h2 class="font-semibold">ຍອດຂາຍຕາມປະເພດອໍເດີ</h2><ReportsReportChart :option="orderOption" :empty="!dashboard.order_type_mix.length"/></UCard></div></template>
	<template v-else-if="activeView==='products'"><div class="grid gap-3 xl:grid-cols-[.8fr_1.2fr]"><UCard><div class="flex items-center justify-between"><h2 class="font-semibold">ສິນຄ້າຂາຍດີ</h2><div class="flex gap-1"><AppButton size="xs" :variant="productMetric==='revenue'?'solid':'soft'" label="ລາຍຮັບ" @click="productMetric='revenue'"/><AppButton size="xs" :variant="productMetric==='quantity'?'solid':'soft'" label="ຈຳນວນ" @click="productMetric='quantity'"/></div></div><ReportsReportChart :option="productOption" :empty="!dashboard.top_products.length"/></UCard><UCard><h2 class="font-semibold">ສິນຄ້າທີ່ຕ້ອງເພີ່ມສະຕັອກ</h2><div v-if="dashboard.low_stock.length" class="mt-4 grid gap-2 sm:grid-cols-2"><div v-for="item in dashboard.low_stock" :key="item.id" class="rounded-md border border-amber-200 bg-amber-50 p-3"><p class="truncate font-semibold">{{item.name}}</p><div class="mt-1 flex justify-between text-xs"><span>{{item.sku}}</span><strong class="text-amber-800">{{num(item.available_base)}} / {{num(item.threshold)}}</strong></div></div></div><p v-else class="py-16 text-center text-sm text-stone-500">ສະຕັອກຢູ່ໃນລະດັບປົກກະຕິ</p></UCard></div>
	<UCard><div class="flex flex-wrap items-center justify-between gap-2"><div><h2 class="font-semibold">ລາຍງານສິນຄ້າທັງໝົດ</h2><p class="text-xs text-stone-500">{{productReport?.pagination.total||0}} ສິນຄ້າໃນຊ່ວງທີ່ເລືອກ</p></div><div class="flex flex-wrap gap-2"><input v-model="productSearch" placeholder="ຄົ້ນຫາສິນຄ້າ / SKU" class="min-w-0 flex-1 rounded-md border border-stone-300 px-3 py-2 text-sm"><select v-model="productCategory" class="rounded-md border border-stone-300 px-3 py-2 text-sm"><option value="">ທຸກໝວດ</option><option v-for="category in productReport?.categories" :key="category.id" :value="category.id">{{category.name}}</option></select><select v-model="productSort" class="rounded-md border border-stone-300 px-3 py-2 text-sm"><option value="revenue">ລາຍຮັບ</option><option value="quantity">ຈຳນວນຂາຍ</option><option value="average_price">ລາຄາສະເລ່ຍ</option><option value="cost">ຕົ້ນທຶນ</option><option value="profit">ກຳໄລ</option><option value="margin">Margin</option></select><AppButton color="neutral" variant="soft" :icon="productOrder==='desc'?'i-heroicons-bars-arrow-down':'i-heroicons-bars-arrow-up'" :label="productOrder==='desc'?'ຫຼາຍ → ໜ້ອຍ':'ໜ້ອຍ → ຫຼາຍ'" @click="productOrder=productOrder==='desc'?'asc':'desc'"/></div></div>
	<div class="mt-4 space-y-2 md:hidden"><button v-for="item in productReport?.items" :key="item.id" class="w-full rounded-md border border-stone-200 p-3 text-left" @click="openProduct(item)"><div class="flex justify-between gap-3"><div class="min-w-0"><p class="truncate font-semibold">{{item.name}}</p><p class="text-xs text-stone-400">{{item.sku}} · {{item.category_name}}</p></div><strong class="text-emerald-700">{{money(item.revenue)}}</strong></div><div class="mt-3 grid grid-cols-3 gap-2 text-xs"><span>ຂາຍ <b>{{num(item.quantity)}}</b></span><span>ກຳໄລ <b>{{money(item.gross_profit)}}</b></span><span>Margin <b>{{item.margin.toFixed(1)}}%</b></span></div></button></div>
	<div class="mt-4 hidden overflow-x-auto md:block"><table class="min-w-[1050px] w-full text-sm"><thead class="bg-stone-50 text-left text-xs text-stone-500"><tr><th class="p-3">ສິນຄ້າ</th><th class="p-3">ໝວດ</th><th class="p-3 text-right">ຈຳນວນ</th><th class="p-3 text-right">ລາຄາສະເລ່ຍ</th><th class="p-3 text-right">ລາຍຮັບ</th><th class="p-3 text-right">ຕົ້ນທຶນ</th><th class="p-3 text-right">ກຳໄລ</th><th class="p-3 text-right">Margin</th><th class="p-3 text-right">ບິນ</th></tr></thead><tbody><tr v-for="item in productReport?.items" :key="item.id" class="cursor-pointer border-t border-stone-100 hover:bg-emerald-50/40" @click="openProduct(item)"><td class="p-3"><strong>{{item.name}}</strong><p class="text-xs text-stone-400">{{item.sku}}</p></td><td class="p-3">{{item.category_name}}</td><td class="p-3 text-right">{{num(item.quantity)}}</td><td class="p-3 text-right">{{money(item.average_price)}}</td><td class="p-3 text-right font-semibold">{{money(item.revenue)}}</td><td class="p-3 text-right">{{money(item.known_cost)}}</td><td class="p-3 text-right text-emerald-700">{{money(item.gross_profit)}}</td><td class="p-3 text-right">{{item.margin.toFixed(1)}}%</td><td class="p-3 text-right">{{item.bill_count}}</td></tr></tbody></table></div><div v-if="productLoading" class="py-8 text-center text-sm text-stone-500">ກຳລັງໂຫຼດ...</div><div v-else-if="!productReport?.items.length" class="py-12 text-center text-sm text-stone-500">ບໍ່ພົບຂໍ້ມູນສິນຄ້າ</div><div class="mt-3 flex justify-end gap-2"><AppButton color="neutral" variant="soft" label="ກ່ອນໜ້າ" :disabled="productPage<=1" @click="productPage--"/><span class="self-center text-sm">{{productPage}} / {{productReport?.pagination.pages||1}}</span><AppButton color="neutral" variant="soft" label="ຕໍ່ໄປ" :disabled="productPage>=(productReport?.pagination.pages||1)" @click="productPage++"/></div></UCard></template>
	<template v-else><div class="grid gap-3 xl:grid-cols-[1.4fr_.6fr]"><UCard><div class="flex justify-between"><h2 class="font-semibold">ຊ່ວງເວລາຂາຍດີ</h2><div class="flex gap-1"><AppButton size="xs" :variant="heatMetric==='revenue'?'solid':'soft'" label="ລາຍຮັບ" @click="heatMetric='revenue'"/><AppButton size="xs" :variant="heatMetric==='bill_count'?'solid':'soft'" label="ບິນ" @click="heatMetric='bill_count'"/></div></div><ReportsReportChart :option="heatOption" height="360px" :empty="!dashboard.heatmap.length"/></UCard><UCard><h2 class="font-semibold">ສັນຍານໜ້າງານ</h2><div class="mt-4 space-y-3"><div class="rounded-md bg-emerald-50 p-4"><p class="text-xs text-emerald-700">ຊ່ວງຂາຍດີສຸດ</p><strong class="mt-1 block text-xl">{{dashboard.operational_signals.peak_period||'-'}}</strong><span class="text-xs">{{money(dashboard.operational_signals.peak_revenue)}}</span></div><div class="rounded-md bg-blue-50 p-4"><p class="text-xs text-blue-700">ວິທີຊຳລະຫຼັກ</p><strong class="mt-1 block text-xl">{{paymentLabel(dashboard.operational_signals.primary_payment_method)}}</strong><span class="text-xs">{{dashboard.operational_signals.primary_payment_percent.toFixed(1)}}%</span></div><div class="rounded-md bg-amber-50 p-4"><p class="text-xs text-amber-700">ຕ້ອງເພີ່ມສະຕັອກ</p><strong class="mt-1 block text-xl">{{dashboard.operational_signals.restock_sku_count}} SKU</strong></div></div></UCard></div><UCard><h2 class="font-semibold">ຜົນງານພະນັກງານ</h2><div class="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3"><div v-for="(staff,index) in dashboard.staff_ranking" :key="staff.id" class="flex items-center gap-3 rounded-md border border-stone-200 p-3"><span class="grid h-9 w-9 place-items-center rounded-full bg-emerald-50 font-semibold text-emerald-700">{{index+1}}</span><div class="min-w-0 flex-1"><p class="truncate font-semibold">{{staff.name}}</p><p class="text-xs text-stone-500">{{staff.bill_count}} ບິນ · ສະເລ່ຍ {{money(staff.average_bill)}}</p></div><strong>{{money(staff.revenue)}}</strong></div></div></UCard></template>
	</template></div>
	<div v-if="selectedProduct" class="fixed inset-0 z-50 flex justify-end bg-stone-950/35" @click.self="selectedProduct=null"><aside class="h-full w-full max-w-xl overflow-y-auto bg-white p-5 shadow-2xl"><div class="flex justify-between"><div><h2 class="text-xl font-semibold">{{selectedProduct.name}}</h2><p class="text-sm text-stone-500">{{selectedProduct.sku}} · {{periodText}}</p></div><AppButton icon="i-heroicons-x-mark" color="neutral" variant="soft" @click="selectedProduct=null"/></div><div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-md bg-stone-50 p-3"><p class="text-xs text-stone-500">ລາຍຮັບ</p><strong>{{money(selectedProduct.revenue)}}</strong></div><div class="rounded-md bg-stone-50 p-3"><p class="text-xs text-stone-500">ຈຳນວນຂາຍ</p><strong>{{num(selectedProduct.quantity)}}</strong></div><div class="rounded-md bg-stone-50 p-3"><p class="text-xs text-stone-500">ກຳໄລ</p><strong>{{money(selectedProduct.gross_profit)}}</strong></div><div class="rounded-md bg-stone-50 p-3"><p class="text-xs text-stone-500">Margin</p><strong>{{selectedProduct.margin.toFixed(1)}}%</strong></div></div><USkeleton v-if="trendLoading" class="mt-5 h-80 rounded-md"/><ReportsReportChart v-else class="mt-5" :option="trendOption" :empty="!productTrend.length"/></aside></div>
	</template></AppSidebarShell></template>
