import "dotenv/config";

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { createClient } from "@libsql/client";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "../..");
const outputDir = path.join(rootDir, "src/models");
const legacyOutputDir = path.join(rootDir, "src/models/generated");
const GENERATED_MARKER = "// Generated by `npm run db:generate-models`";

function getDbConfig() {
	const url = process.env.TURSO_DATABASE_URL || process.env.DATABASE_URL || "file:./database.db";
	const authToken = url.startsWith("file:") ? undefined : process.env.TURSO_AUTH_TOKEN;

	return { url, authToken };
}

function quoteIdentifier(value) {
	return `"${String(value).replace(/"/g, "\"\"")}"`;
}

function toPascalCase(value) {
	return value
		.split(/[^a-zA-Z0-9]+/)
		.filter(Boolean)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
		.join("");
}

function singularizeWord(value) {
	if (value.endsWith("ies") && value.length > 3) return `${value.slice(0, -3)}y`;
	if (
		(value.endsWith("ches") || value.endsWith("shes") || value.endsWith("xes") || value.endsWith("zes")) &&
		value.length > 4
	) {
		return value.slice(0, -2);
	}
	if (value.endsWith("sses") && value.length > 4) return value.slice(0, -2);
	if (value.endsWith("ses") && value.length > 3) return value.slice(0, -1);
	if (value.endsWith("s") && !value.endsWith("ss") && value.length > 1) return value.slice(0, -1);
	return value;
}

function tableNameToEntityName(tableName) {
	const parts = tableName.split("_").filter(Boolean);
	if (parts.length === 0) return "GeneratedModel";

	const normalized = parts.map((part, index) => {
		if (index !== parts.length - 1) return part;
		return singularizeWord(part);
	});

	return toPascalCase(normalized.join("_"));
}

function sqliteTypeToTs(type) {
	const normalized = String(type || "").toUpperCase();

	if (normalized.includes("INT")) return "number";
	if (normalized.includes("CHAR") || normalized.includes("CLOB") || normalized.includes("TEXT")) return "string";
	if (
		normalized.includes("REAL") ||
		normalized.includes("FLOA") ||
		normalized.includes("DOUB") ||
		normalized.includes("NUM") ||
		normalized.includes("DEC")
	) {
		return "number";
	}
	if (normalized.includes("BLOB")) return "Uint8Array";

	return "unknown";
}

function isNullable(column) {
	return !column.notNull && column.primaryKeyOrder === 0;
}

function isAutoincrementPrimaryKey(column, createSql) {
	return column.primaryKeyOrder > 0 &&
		String(column.type || "").toUpperCase().includes("INT") &&
		/autoincrement/i.test(createSql || "");
}

function buildPropertyLine(column, options = {}) {
	const optional = options.optional ? "?" : "";
	const nullable = isNullable(column) ? " | null" : "";
	return `\t${column.name}${optional}: ${sqliteTypeToTs(column.type)}${nullable};`;
}

function buildTableFile({ tableName, entityName, createSql, columns }) {
	const primaryKeys = columns.filter((column) => column.primaryKeyOrder > 0);
	const createLines = columns.map((column) => buildPropertyLine(column, {
		optional: column.primaryKeyOrder > 0 || isNullable(column) || column.defaultValue !== null || isAutoincrementPrimaryKey(column, createSql),
	}));
	const updateLines = columns
		.filter((column) => column.primaryKeyOrder === 0)
		.map((column) => buildPropertyLine(column, { optional: true }));

	const rowLines = columns.map((column) => buildPropertyLine(column));
	const primaryKeyValues = primaryKeys.map((column) => `"${column.name}"`).join(", ");
	const columnValues = columns.map((column) => `"${column.name}"`).join(", ");
	const updateTypeBody = updateLines.length > 0 ? updateLines.join("\n") : "\t[key: string]: never;";

	return `/* eslint-disable */
${GENERATED_MARKER} from the current database schema.
// Do not edit this file manually.

export const ${entityName.toUpperCase()}_TABLE = "${tableName}";
export const ${entityName.toUpperCase()}_COLUMNS = [${columnValues}] as const;
export const ${entityName.toUpperCase()}_PRIMARY_KEYS = [${primaryKeyValues}] as const;

export type ${entityName}Row = {
${rowLines.join("\n")}
};

export type ${entityName}CreateInput = {
${createLines.join("\n")}
};

export type ${entityName}UpdateInput = {
${updateTypeBody}
};

export type ${entityName} = ${entityName}Row;
export type Create${entityName}Input = ${entityName}CreateInput;
export type Update${entityName}Input = ${entityName}UpdateInput;
`;
}

async function getSchema(client, targetTable) {
	const result = targetTable
		? await client.execute({
			sql: `
				SELECT name, type, sql
				FROM sqlite_master
				WHERE type IN ('table', 'view')
					AND name NOT LIKE 'sqlite_%'
					AND name = ?
				ORDER BY type, name
			`,
			args: [ targetTable ],
		})
		: await client.execute(`
			SELECT name, type, sql
			FROM sqlite_master
			WHERE type IN ('table', 'view')
				AND name NOT LIKE 'sqlite_%'
			ORDER BY type, name
		`);

	const tables = [];

	for (const row of result.rows) {
		const tableName = String(row.name);
		const columnsResult = await client.execute(`PRAGMA table_info(${quoteIdentifier(tableName)})`);

		tables.push({
			tableName,
			entityName: tableNameToEntityName(tableName),
			createSql: String(row.sql || ""),
			columns: columnsResult.rows.map((column) => ({
				name: String(column.name),
				type: String(column.type || ""),
				notNull: Number(column.notnull) === 1 || Number(column.pk || 0) > 0,
				defaultValue: column.dflt_value ?? null,
				primaryKeyOrder: Number(column.pk || 0),
			})),
		});
	}

	return tables;
}

async function isGeneratedFile(filePath) {
	try {
		const content = await fs.readFile(filePath, "utf8");
		return content.includes(GENERATED_MARKER);
	} catch {
		return false;
	}
}

async function cleanOutputDirectory() {
	await fs.mkdir(outputDir, { recursive: true });
	const entries = await fs.readdir(outputDir);

	await Promise.all(entries.map(async (entry) => {
		if (!entry.endsWith(".ts")) return;
		const filePath = path.join(outputDir, entry);
		if (await isGeneratedFile(filePath)) {
			await fs.rm(filePath, { force: true });
		}
	}));

	await fs.rm(legacyOutputDir, { recursive: true, force: true });
}

async function writeIndexFile() {
	const entries = await fs.readdir(outputDir);
	const generatedFiles = entries
		.filter((entry) => entry.endsWith(".ts") && entry !== "generated.ts")
		.sort((left, right) => left.localeCompare(right));

	const generatedEntries = [];
	for (const entry of generatedFiles) {
		const filePath = path.join(outputDir, entry);
		if (await isGeneratedFile(filePath)) {
			generatedEntries.push(entry);
		}
	}

	const exports = generatedEntries.map((entry) => `export * from "./${entry.replace(/\.ts$/, "")}";`);
	const content = `/* eslint-disable */
${GENERATED_MARKER}.
// Do not edit this file manually.

${exports.join("\n")}
`;

	await fs.writeFile(path.join(outputDir, "generated.ts"), content, "utf8");
}

async function shouldSkipFile(filePath) {
	try {
		await fs.access(filePath);
		return !(await isGeneratedFile(filePath));
	} catch {
		return false;
	}
}

async function main() {
	const targetTable = process.argv[2]?.trim() || null;
	const { url, authToken } = getDbConfig();
	const client = createClient({
		url,
		...(authToken ? { authToken } : {}),
	});

	const schema = await getSchema(client, targetTable);
	if (schema.length === 0) {
		throw new Error(targetTable ? `Table not found: ${targetTable}` : "No tables found");
	}

	if (!targetTable) {
		await cleanOutputDirectory();
	} else {
		await fs.mkdir(outputDir, { recursive: true });
	}

	const generated = [];

	for (const table of schema) {
		const fileName = `${table.entityName}.ts`;
		const filePath = path.join(outputDir, fileName);

		const content = buildTableFile(table);
		await fs.writeFile(filePath, content, "utf8");
		generated.push({
			table: table.tableName,
			file: fileName,
			columns: table.columns.length,
		});
	}

	await writeIndexFile();

	process.stdout.write(JSON.stringify({
		driver: url.startsWith("libsql://") ? "turso" : url.startsWith("file:") ? "sqlite" : "unknown",
		outputDir,
		generated,
	}, null, 2) + "\n");
}

main().catch((error) => {
	process.stderr.write(`${error.stack || error.message || String(error)}\n`);
	process.exit(1);
});
