import { InValue } from "@libsql/client";

import { DbConn } from "@connections/DbConn";
import { StoreInterface } from "@interfaces/StoreInterface";
import { ApiError } from "@middlewares/ApiError";

export type ReportPreset = "today" | "yesterday" | "this_week" | "last_week" | "this_month" | "last_month" | "custom" | "7d" | "30d";
export type ProductReportSort = "quantity" | "average_price" | "revenue" | "cost" | "profit" | "margin";
type Period = { from: string; to: string; date_from: string; date_to: string; days: number };
export type ReportPeriodInput = { preset: ReportPreset; dateFrom?: string; dateTo?: string; timezoneOffset: number; businessDayStartMinutes?: number };

const DAY = 86_400_000;
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
function number(value: unknown): number { const parsed=Number(value); return Number.isFinite(parsed)?parsed:0; }
function row(result:any):Record<string,unknown>{return(result?.rows?.[0]||{}) as Record<string,unknown>;}
function localDate(ms:number,offsetMs:number):string{return new Date(ms+offsetMs).toISOString().slice(0,10);}
function utcFromLocalDate(value:string,offsetMs:number):number{
	if(!DATE_RE.test(value)) throw ApiError.BadRequestError("Invalid report date");
	const [year,month,day]=value.split("-").map(Number); const valueMs=Date.UTC(year,month-1,day)-offsetMs;
	if(localDate(valueMs,offsetMs)!==value) throw ApiError.BadRequestError("Invalid report date"); return valueMs;
}

export function resolveReportPeriods(input:ReportPeriodInput,reference=new Date()):{current:Period;previous:Period;preset:ReportPreset}{
	const offsetMs=input.timezoneOffset*60_000,startMinutes=Math.min(1439,Math.max(0,Math.trunc(number(input.businessDayStartMinutes)))),startMs=startMinutes*60_000; const localNow=reference.getTime()+offsetMs;
	const nowDate=new Date(localNow); const calendarToday=Date.UTC(nowDate.getUTCFullYear(),nowDate.getUTCMonth(),nowDate.getUTCDate()),todayLocal=calendarToday+(localNow-calendarToday<startMs?-DAY:0),businessDate=new Date(todayLocal);
	let fromLocal=todayLocal+startMs,toLocal=fromLocal+DAY; let preset=input.preset;
	if(preset==="7d"){fromLocal=toLocal-7*DAY;} else if(preset==="30d"){fromLocal=toLocal-30*DAY;}
	else if(preset==="yesterday"){toLocal=todayLocal+startMs;fromLocal=toLocal-DAY;}
	else if(preset==="this_week"){const weekday=(businessDate.getUTCDay()+6)%7;fromLocal=todayLocal-weekday*DAY+startMs;}
	else if(preset==="last_week"){const weekday=(businessDate.getUTCDay()+6)%7;toLocal=todayLocal-weekday*DAY+startMs;fromLocal=toLocal-7*DAY;}
	else if(preset==="this_month"){fromLocal=Date.UTC(businessDate.getUTCFullYear(),businessDate.getUTCMonth(),1)+startMs;}
	else if(preset==="last_month"){toLocal=Date.UTC(businessDate.getUTCFullYear(),businessDate.getUTCMonth(),1)+startMs;fromLocal=Date.UTC(businessDate.getUTCFullYear(),businessDate.getUTCMonth()-1,1)+startMs;}
	else if(preset==="custom"){
		if(!input.dateFrom||!input.dateTo) throw ApiError.BadRequestError("date_from and date_to are required for custom range");
		fromLocal=utcFromLocalDate(input.dateFrom,0)+startMs;toLocal=utcFromLocalDate(input.dateTo,0)+DAY+startMs;
	}
	const days=Math.round((toLocal-fromLocal)/DAY); if(days<1||days>366) throw ApiError.BadRequestError("Report range must be between 1 and 366 days");
	const from=fromLocal-offsetMs,to=toLocal-offsetMs,previousFrom=from-days*DAY;
	const make=(a:number,b:number):Period=>({from:new Date(a).toISOString(),to:new Date(b).toISOString(),date_from:localDate(a-startMs,offsetMs),date_to:localDate(b-DAY-startMs,offsetMs),days:Math.round((b-a)/DAY)});
	return{current:make(from,to),previous:make(previousFrom,from),preset};
}

function comparison(current:number,previous:number){return previous===0?{value:null,available:false}:{value:(current-previous)/Math.abs(previous)*100,available:true};}
function bucketMode(days:number){return days===1?"hour":days<=31?"day":"week";}
function bucketLabel(ms:number,mode:string,offsetMs:number){
	const date=new Date(ms+offsetMs); if(mode==="hour")return `${String(date.getUTCHours()).padStart(2,"0")}:00`;
	if(mode==="week"){const weekday=(date.getUTCDay()+6)%7;return new Date(date.getTime()-weekday*DAY).toISOString().slice(0,10);}
	return date.toISOString().slice(0,10);
}
function fillSeries(rows:any[],period:Period,timezoneOffset:number){
	const offsetMs=timezoneOffset*60_000,mode=bucketMode(period.days),map=new Map(rows.map(item=>[String(item.label),item])); const output:any[]=[];
	const step=mode==="hour"?3_600_000:mode==="day"?DAY:7*DAY;
	for(let ms=new Date(period.from).getTime();ms<new Date(period.to).getTime();ms+=step){const label=bucketLabel(ms,mode,offsetMs);const item=map.get(label)||{};output.push({label,revenue:number(item.revenue),gross_sales:number(item.gross_sales),discount:number(item.discount),vat_amount:number(item.vat_amount),bill_count:number(item.bill_count),known_cost:number(item.known_cost),unknown_cost_revenue:number(item.unknown_cost_revenue),gross_profit:number(item.revenue)-number(item.known_cost)-number(item.unknown_cost_revenue)});}
	return output;
}

export class ReportInterface{
	private static initialized=false;
	private static async ensureIndexes(){await StoreInterface.ensureColumns();if(this.initialized)return;const db=DbConn.getClient();await db.batch([
		"CREATE INDEX IF NOT EXISTS idx_reports_orders_store_state_paid ON orders(store_id,status,payment_status,paid_at)",
		"CREATE INDEX IF NOT EXISTS idx_reports_orders_store_paid_channel ON orders(store_id,paid_at,service_mode,channel)",
		"CREATE INDEX IF NOT EXISTS idx_reports_items_order_product ON order_items(order_id,product_id,line_status,is_gift)",
	],"write");this.initialized=true;}
	private static async periods(storeId:string,input:ReportPeriodInput){const result=await DbConn.getClient().execute({sql:"SELECT business_day_start_minutes FROM stores WHERE id=? LIMIT 1",args:[storeId]});return resolveReportPeriods({...input,businessDayStartMinutes:number(result.rows[0]?.business_day_start_minutes)});}
	private static clauses(storeId:string,period:Period){return{paid:"o.store_id=? AND o.status='completed' AND o.payment_status='paid' AND o.paid_at>=? AND o.paid_at<?",args:[storeId,period.from,period.to] as InValue[]};}

	static async dashboard(storeId:string,input:ReportPeriodInput):Promise<any>{
		await this.ensureIndexes();const db=DbConn.getClient(),periods=await this.periods(storeId,input),current=this.clauses(storeId,periods.current),previous=this.clauses(storeId,periods.previous);
		const modifier=`${input.timezoneOffset>=0?"+":""}${input.timezoneOffset} minutes`,mode=bucketMode(periods.current.days);
		const seriesExpr=mode==="hour"?`strftime('%H:00',o.paid_at,'${modifier}')`:mode==="day"?`strftime('%Y-%m-%d',o.paid_at,'${modifier}')`:`date(o.paid_at,'${modifier}','-' || ((strftime('%w',o.paid_at,'${modifier}')+6)%7) || ' days')`;
		const itemWhere=`${current.paid} AND COALESCE(oi.line_status,'sent')!='cancelled'`;
		const results=await db.batch([
			{sql:`SELECT COUNT(*) bill_count,COALESCE(SUM(o.total),0) revenue,COALESCE(SUM(o.subtotal),0) gross_sales,COALESCE(SUM(o.discount),0) discount,COALESCE(SUM(o.vat_amount),0) vat_amount,COALESCE(SUM(o.shipping_fee_charged),0) shipping_revenue,COALESCE(SUM(o.shipping_cost),0) shipping_cost,COALESCE(AVG(o.total),0) average_bill,COUNT(CASE WHEN COALESCE(o.discount,0)>0 THEN 1 END) discounted_bill_count FROM orders o WHERE ${current.paid}`,args:current.args},
			{sql:`SELECT COUNT(*) bill_count,COALESCE(SUM(o.total),0) revenue,COALESCE(AVG(o.total),0) average_bill FROM orders o WHERE ${previous.paid}`,args:previous.args},
			{sql:"SELECT COUNT(DISTINCT id) total,COALESCE(SUM(total),0) amount FROM orders WHERE store_id=? AND COALESCE(closed_at,paid_at,created_at)>=? AND COALESCE(closed_at,paid_at,created_at)<? AND (status='cancelled' OR payment_status='refunded')",args:current.args},
			{sql:"SELECT COUNT(DISTINCT id) total,COALESCE(SUM(total),0) amount FROM orders WHERE store_id=? AND COALESCE(closed_at,paid_at,created_at)>=? AND COALESCE(closed_at,paid_at,created_at)<? AND (status='cancelled' OR payment_status='refunded')",args:previous.args},
			{sql:`SELECT ${seriesExpr} label,COALESCE(SUM(o.total),0) revenue,COALESCE(SUM(o.subtotal),0) gross_sales,COALESCE(SUM(o.discount),0) discount,COALESCE(SUM(o.vat_amount),0) vat_amount,COUNT(*) bill_count,COALESCE(SUM((SELECT SUM(CASE WHEN oi.cost_source_at_sale IN ('purchase','manual') THEN oi.cost_base_at_sale*oi.qty_base ELSE 0 END) FROM order_items oi WHERE oi.order_id=o.id AND COALESCE(oi.line_status,'sent')!='cancelled')),0) known_cost,COALESCE(SUM((SELECT SUM(CASE WHEN oi.cost_source_at_sale='unknown' AND COALESCE(oi.is_gift,0)=0 THEN oi.line_total ELSE 0 END) FROM order_items oi WHERE oi.order_id=o.id AND COALESCE(oi.line_status,'sent')!='cancelled')),0) unknown_cost_revenue FROM orders o WHERE ${current.paid} GROUP BY label ORDER BY label`,args:current.args},
			{sql:`SELECT COALESCE(NULLIF(TRIM(o.payment_method),''),'other') method,COALESCE(SUM(o.total),0) amount,COUNT(*) bill_count FROM orders o WHERE ${current.paid} GROUP BY method ORDER BY amount DESC`,args:current.args},
			{sql:`SELECT p.id,p.name,p.sku,COALESCE(SUM(oi.qty_base),0) quantity,COALESCE(SUM(oi.line_total),0) revenue FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN products p ON p.id=oi.product_id WHERE ${itemWhere} AND COALESCE(oi.is_gift,0)=0 GROUP BY p.id,p.name,p.sku ORDER BY revenue DESC LIMIT 10`,args:current.args},
			{sql:`SELECT oi.product_id,COALESCE(SUM(oi.line_total),0) revenue FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE ${previous.paid} AND COALESCE(oi.line_status,'sent')!='cancelled' AND COALESCE(oi.is_gift,0)=0 GROUP BY oi.product_id`,args:previous.args},
			{sql:`SELECT COALESCE(u.id,o.created_by,'deleted') id,COALESCE(NULLIF(u.name,''),NULLIF(u.email,''),'Unknown user') name,COUNT(*) bill_count,COALESCE(SUM(o.total),0) revenue,COALESCE(AVG(o.total),0) average_bill FROM orders o LEFT JOIN users u ON u.id=o.created_by WHERE ${current.paid} GROUP BY 1,2 ORDER BY revenue DESC LIMIT 10`,args:current.args},
			{sql:`SELECT p.id,p.name,p.sku,COALESCE(b.available_base,0) available_base,CASE WHEN COALESCE(p.low_stock_threshold,0)>0 THEN p.low_stock_threshold ELSE COALESCE(s.low_stock_threshold,0) END threshold FROM products p JOIN stores s ON s.id=p.store_id LEFT JOIN inventory_balances b ON b.store_id=p.store_id AND b.product_id=p.id WHERE p.store_id=? AND p.active=1 AND p.deleted_at IS NULL AND p.inventory_mode='tracked' AND CASE WHEN COALESCE(p.low_stock_threshold,0)>0 THEN p.low_stock_threshold ELSE COALESCE(s.low_stock_threshold,0) END>0 AND COALESCE(b.available_base,0)<=CASE WHEN COALESCE(p.low_stock_threshold,0)>0 THEN p.low_stock_threshold ELSE COALESCE(s.low_stock_threshold,0) END ORDER BY available_base,p.name LIMIT 20`,args:[storeId]},
			{sql:`SELECT COALESCE(SUM(CASE WHEN oi.cost_source_at_sale IN ('purchase','manual') THEN oi.cost_base_at_sale*oi.qty_base ELSE 0 END),0) known_cost,COALESCE(SUM(CASE WHEN oi.cost_source_at_sale='unknown' AND COALESCE(oi.is_gift,0)=0 THEN oi.line_total ELSE 0 END),0) unknown_cost_revenue,COUNT(DISTINCT CASE WHEN oi.cost_source_at_sale='unknown' THEN o.id END) unknown_cost_bills FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE ${itemWhere}`,args:current.args},
			{sql:"SELECT COALESCE(currency,'LAK') currency FROM stores WHERE id=?",args:[storeId]},
			{sql:`SELECT COALESCE(NULLIF(o.service_mode,''),NULLIF(o.channel,''),'other') type,COALESCE(SUM(o.total),0) revenue,COUNT(*) bill_count FROM orders o WHERE ${current.paid} GROUP BY type ORDER BY revenue DESC`,args:current.args},
			{sql:`SELECT CAST(strftime('%w',o.paid_at,'${modifier}') AS INTEGER) weekday,CAST(strftime('%H',o.paid_at,'${modifier}') AS INTEGER) hour,COALESCE(SUM(o.total),0) revenue,COUNT(*) bill_count FROM orders o WHERE ${current.paid} GROUP BY weekday,hour`,args:current.args},
			{sql:`SELECT ${seriesExpr} label,COALESCE(NULLIF(o.service_mode,''),NULLIF(o.channel,''),'other') type,COALESCE(SUM(o.total),0) revenue,COUNT(*) bill_count FROM orders o WHERE ${current.paid} GROUP BY label,type ORDER BY label`,args:current.args},
			{sql:`SELECT p.id,p.name,COALESCE(SUM(oi.qty_base),0) quantity,COALESCE(SUM(oi.line_total),0) revenue FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN products p ON p.id=oi.product_id WHERE ${itemWhere} AND COALESCE(oi.is_gift,0)=0 GROUP BY p.id,p.name ORDER BY revenue DESC`,args:current.args},
			{sql:`SELECT COALESCE(pc.id,'uncategorized') id,COALESCE(pc.name,'Uncategorized') name,COALESCE(SUM(CASE WHEN COALESCE(oi.is_gift,0)=0 THEN oi.qty_base ELSE 0 END),0) quantity,COALESCE(SUM(CASE WHEN COALESCE(oi.is_gift,0)=0 THEN oi.line_total ELSE 0 END),0) revenue,COALESCE(SUM(CASE WHEN oi.cost_source_at_sale IN ('purchase','manual') THEN oi.cost_base_at_sale*oi.qty_base ELSE 0 END),0) known_cost,COALESCE(SUM(CASE WHEN COALESCE(oi.is_gift,0)=1 AND oi.cost_source_at_sale IN ('purchase','manual') THEN oi.cost_base_at_sale*oi.qty_base ELSE 0 END),0) gift_cost,COALESCE(SUM(CASE WHEN oi.cost_source_at_sale='unknown' AND COALESCE(oi.is_gift,0)=0 THEN oi.line_total ELSE 0 END),0) unknown_cost_revenue FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN products p ON p.id=oi.product_id LEFT JOIN product_categories pc ON pc.id=p.category_id WHERE ${itemWhere} GROUP BY pc.id,pc.name HAVING revenue>0 OR gift_cost>0 ORDER BY revenue DESC`,args:current.args},
			{sql:`SELECT op.promotion_id,op.promotion_name,op.promotion_type,COUNT(DISTINCT op.order_id) bill_count,GROUP_CONCAT(DISTINCT op.order_id) order_ids,COALESCE(SUM(op.applications),0) applications,COALESCE(SUM(op.discount_amount),0) discount_amount,COALESCE(SUM(g.gift_quantity),0) gift_quantity,COALESCE(SUM(g.gift_cost),0) gift_cost FROM order_promotions op JOIN orders o ON o.id=op.order_id LEFT JOIN (SELECT order_id,promotion_id,SUM(qty_base) gift_quantity,SUM(CASE WHEN cost_source_at_sale IN ('purchase','manual') THEN cost_base_at_sale*qty_base ELSE 0 END) gift_cost FROM order_items WHERE COALESCE(is_gift,0)=1 AND COALESCE(line_status,'sent')!='cancelled' GROUP BY order_id,promotion_id) g ON g.order_id=op.order_id AND g.promotion_id=op.promotion_id WHERE ${current.paid} GROUP BY op.promotion_id,op.promotion_name,op.promotion_type ORDER BY bill_count DESC,op.promotion_name`,args:current.args},
			{sql:`SELECT COUNT(CASE WHEN p.inventory_mode='tracked' AND COALESCE(b.available_base,0)<=0 THEN 1 END) out_of_stock_count,COUNT(CASE WHEN p.inventory_mode='tracked' AND COALESCE(b.available_base,0)<0 THEN 1 END) negative_stock_count,COALESCE(SUM(CASE WHEN p.inventory_mode='tracked' THEN COALESCE(b.available_base,0)*COALESCE(p.cost_base,0) ELSE 0 END),0) inventory_value,(SELECT COUNT(*) FROM products np WHERE np.store_id=? AND np.active=1 AND np.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM order_items noi JOIN orders no ON no.id=noi.order_id WHERE noi.product_id=np.id AND no.store_id=? AND no.status='completed' AND no.payment_status='paid' AND no.paid_at>=? AND no.paid_at<? AND COALESCE(noi.line_status,'sent')!='cancelled')) no_sales_count FROM products p LEFT JOIN inventory_balances b ON b.store_id=p.store_id AND b.product_id=p.id WHERE p.store_id=? AND p.active=1 AND p.deleted_at IS NULL`,args:[storeId,storeId,periods.current.from,periods.current.to,storeId]},
		],"read");
		const currentSummary=row(results[0]),previousSummary=row(results[1]),revenue=number(currentSummary.revenue),grossSales=number(currentSummary.gross_sales),discount=number(currentSummary.discount),bills=number(currentSummary.bill_count),average=number(currentSummary.average_bill),cancelled=number(row(results[2]).total),cancelledAmount=number(row(results[2]).amount),prevCancelled=number(row(results[3]).total);
		const profit=row(results[10]),knownCost=number(profit.known_cost),unknownRevenue=number(profit.unknown_cost_revenue),knownRevenue=Math.max(0,revenue-unknownRevenue),grossProfit=knownRevenue-knownCost;
		const paymentRows=results[5].rows as any[],paymentTotal=paymentRows.reduce((sum,item)=>sum+number(item.amount),0),previousProducts=new Map((results[7].rows as any[]).map(item=>[String(item.product_id),number(item.revenue)]));
		const series=fillSeries(results[4].rows as any[],periods.current,input.timezoneOffset),peak=[...series].sort((a,b)=>b.revenue-a.revenue)[0]||null;
		const lowStock=(results[9].rows as any[]).map(item=>({id:String(item.id),name:String(item.name),sku:String(item.sku||""),available_base:number(item.available_base),threshold:number(item.threshold)}));
		const productMixRows=(results[15].rows as any[]),productRevenueTotal=productMixRows.reduce((sum,item)=>sum+number(item.revenue),0);
		const productMix=productMixRows.slice(0,8).map(item=>({id:String(item.id),name:String(item.name),quantity:number(item.quantity),revenue:number(item.revenue),percent:productRevenueTotal?number(item.revenue)/productRevenueTotal*100:0}));
		if(productMixRows.length>8){const other=productMixRows.slice(8).reduce((sum,item)=>({quantity:sum.quantity+number(item.quantity),revenue:sum.revenue+number(item.revenue)}),{quantity:0,revenue:0});productMix.push({id:"other",name:"Other products",quantity:other.quantity,revenue:other.revenue,percent:productRevenueTotal?other.revenue/productRevenueTotal*100:0});}
		const categoryPerformance=(results[16].rows as any[]).map(item=>{const categoryRevenue=number(item.revenue),unknownCostRevenue=number(item.unknown_cost_revenue),coveredRevenue=Math.max(0,categoryRevenue-unknownCostRevenue),categoryKnownCost=number(item.known_cost),categoryProfit=coveredRevenue-categoryKnownCost;return{id:String(item.id),name:String(item.name),quantity:number(item.quantity),revenue:categoryRevenue,known_cost:categoryKnownCost,gift_cost:number(item.gift_cost),gross_profit:categoryProfit,margin:coveredRevenue?categoryProfit/coveredRevenue*100:0,cost_coverage_percent:categoryRevenue?coveredRevenue/categoryRevenue*100:0};});
		const promotionRows=(results[17].rows as any[]),promotionOrderIds=new Set(promotionRows.flatMap(item=>String(item.order_ids||"").split(",").filter(Boolean)));
		const promotionPerformance=promotionRows.map(item=>({promotion_id:String(item.promotion_id),name:String(item.promotion_name),type:String(item.promotion_type),bill_count:number(item.bill_count),applications:number(item.applications),discount_amount:number(item.discount_amount),gift_quantity:number(item.gift_quantity),gift_cost:number(item.gift_cost)}));
		const promotionSummary=promotionPerformance.reduce((sum,item)=>({promotion_bill_count:promotionOrderIds.size,applications:sum.applications+item.applications,discount_amount:sum.discount_amount+item.discount_amount,gift_quantity:sum.gift_quantity+item.gift_quantity,gift_cost:sum.gift_cost+item.gift_cost}),{promotion_bill_count:promotionOrderIds.size,applications:0,discount_amount:0,gift_quantity:0,gift_cost:0});
		const inventorySignals=row(results[18]);
		return{currency:String(row(results[11]).currency||"LAK"),preset:periods.preset,timezone_offset:input.timezoneOffset,period:periods.current,comparison_period:periods.previous,generated_at:new Date().toISOString(),
			summary:{revenue,gross_sales:grossSales,discount,discount_rate_percent:grossSales?discount/grossSales*100:0,discounted_bill_count:number(currentSummary.discounted_bill_count),vat_amount:number(currentSummary.vat_amount),shipping_revenue:number(currentSummary.shipping_revenue),shipping_cost:number(currentSummary.shipping_cost),bill_count:bills,average_bill:average,cancelled_refunded_count:cancelled,cancelled_refunded_amount:cancelledAmount,gross_profit:grossProfit,gross_margin_percent:knownRevenue?grossProfit/knownRevenue*100:0,comparison:{revenue:comparison(revenue,number(previousSummary.revenue)),bill_count:comparison(bills,number(previousSummary.bill_count)),average_bill:comparison(average,number(previousSummary.average_bill)),cancelled_refunded_count:comparison(cancelled,prevCancelled)}},
			profitability:{revenue,known_cost_revenue:knownRevenue,known_cost:knownCost,known_gross_profit:grossProfit,gross_margin_percent:knownRevenue?grossProfit/knownRevenue*100:0,cost_coverage_percent:revenue?knownRevenue/revenue*100:0,unknown_cost_revenue:unknownRevenue,unknown_cost_bills:number(profit.unknown_cost_bills),bill_count:bills},sales_series:series,
			payment_mix:paymentRows.map(item=>({method:String(item.method),amount:number(item.amount),bill_count:number(item.bill_count),percent:paymentTotal?number(item.amount)/paymentTotal*100:0})),
			top_products:(results[6].rows as any[]).map(item=>{const itemRevenue=number(item.revenue),old=previousProducts.get(String(item.id))||0;return{id:String(item.id),name:String(item.name),sku:String(item.sku||""),quantity:number(item.quantity),revenue:itemRevenue,percent:productRevenueTotal?itemRevenue/productRevenueTotal*100:0,comparison:comparison(itemRevenue,old)};}),product_mix:productMix,category_performance:categoryPerformance,promotion_summary:promotionSummary,promotion_performance:promotionPerformance,
			staff_ranking:(results[8].rows as any[]).map(item=>({id:String(item.id),name:String(item.name),bill_count:number(item.bill_count),revenue:number(item.revenue),average_bill:number(item.average_bill)})),low_stock:lowStock,
			order_type_mix:(results[12].rows as any[]).map(item=>({type:String(item.type),revenue:number(item.revenue),bill_count:number(item.bill_count)})),heatmap:(results[13].rows as any[]).map(item=>({weekday:number(item.weekday),hour:number(item.hour),revenue:number(item.revenue),bill_count:number(item.bill_count)})),order_type_series:(results[14].rows as any[]).map(item=>({label:String(item.label),type:String(item.type),revenue:number(item.revenue),bill_count:number(item.bill_count)})),
			operational_signals:{peak_period:peak?.label||null,peak_revenue:peak?.revenue||0,primary_payment_method:paymentRows[0]?String(paymentRows[0].method):null,primary_payment_percent:paymentRows[0]&&paymentTotal?number(paymentRows[0].amount)/paymentTotal*100:0,restock_sku_count:lowStock.length,out_of_stock_count:number(inventorySignals.out_of_stock_count),negative_stock_count:number(inventorySignals.negative_stock_count),no_sales_count:number(inventorySignals.no_sales_count),inventory_value:number(inventorySignals.inventory_value)}};
	}

	static async products(storeId:string,input:ReportPeriodInput,options:{search?:string;categoryId?:string;sort:ProductReportSort;order:"asc"|"desc";page:number;limit:number}){
		await this.ensureIndexes();const db=DbConn.getClient(),periods=await this.periods(storeId,input),current=this.clauses(storeId,periods.current),previous=this.clauses(storeId,periods.previous);const where=[current.paid,"COALESCE(oi.line_status,'sent')!='cancelled'","COALESCE(oi.is_gift,0)=0"],args=[...current.args] as InValue[];
		if(options.search){where.push("(LOWER(p.name) LIKE ? OR LOWER(p.sku) LIKE ?)");const term=`%${options.search.toLowerCase()}%`;args.push(term,term);}if(options.categoryId){where.push(options.categoryId==="uncategorized"?"p.category_id IS NULL":"p.category_id=?");if(options.categoryId!=="uncategorized")args.push(options.categoryId);}
		const aggregate=`FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN products p ON p.id=oi.product_id LEFT JOIN product_categories pc ON pc.id=p.category_id WHERE ${where.join(" AND ")}`;
		const sortMap:Record<ProductReportSort,string>={quantity:"quantity",average_price:"average_price",revenue:"revenue",cost:"known_cost",profit:"gross_profit",margin:"margin"},direction=options.order.toUpperCase();
		const baseSelect=`SELECT p.id,p.name,p.sku,COALESCE(pc.name,'Uncategorized') category_name,COALESCE(SUM(oi.qty_base),0) quantity,COALESCE(SUM(oi.line_total),0) revenue,CASE WHEN SUM(oi.qty_base)>0 THEN SUM(oi.line_total)/SUM(oi.qty_base) ELSE 0 END average_price,COALESCE(SUM(CASE WHEN oi.cost_source_at_sale IN ('purchase','manual') THEN oi.cost_base_at_sale*oi.qty_base ELSE 0 END),0) known_cost,COALESCE(SUM(oi.line_total),0)-COALESCE(SUM(CASE WHEN oi.cost_source_at_sale IN ('purchase','manual') THEN oi.cost_base_at_sale*oi.qty_base ELSE 0 END),0) gross_profit,CASE WHEN SUM(oi.line_total)>0 THEN (SUM(oi.line_total)-SUM(CASE WHEN oi.cost_source_at_sale IN ('purchase','manual') THEN oi.cost_base_at_sale*oi.qty_base ELSE 0 END))*100.0/SUM(oi.line_total) ELSE 0 END margin,COUNT(DISTINCT o.id) bill_count`;
		const previousSql=`SELECT oi.product_id,COALESCE(SUM(oi.line_total),0) revenue FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE ${previous.paid} AND COALESCE(oi.line_status,'sent')!='cancelled' AND COALESCE(oi.is_gift,0)=0 GROUP BY oi.product_id`;
		const result=await db.batch([{sql:`SELECT COUNT(*) total FROM (SELECT p.id ${aggregate} GROUP BY p.id)`,args},{sql:`${baseSelect} ${aggregate} GROUP BY p.id,p.name,p.sku,pc.name ORDER BY ${sortMap[options.sort]} ${direction},p.name LIMIT ? OFFSET ?`,args:[...args,options.limit,(options.page-1)*options.limit]},{sql:previousSql,args:previous.args},{sql:"SELECT id,name FROM product_categories WHERE store_id=? ORDER BY sort_order,name",args:[storeId]}],"read");
		const previousMap=new Map((result[2].rows as any[]).map(item=>[String(item.product_id),number(item.revenue)]));return{period:periods.current,items:(result[1].rows as any[]).map(item=>{const revenue=number(item.revenue);return{id:String(item.id),name:String(item.name),sku:String(item.sku||""),category_name:String(item.category_name),quantity:number(item.quantity),average_price:number(item.average_price),revenue,known_cost:number(item.known_cost),gross_profit:number(item.gross_profit),margin:number(item.margin),bill_count:number(item.bill_count),comparison:comparison(revenue,previousMap.get(String(item.id))||0)};}),categories:[{id:"uncategorized",name:"Uncategorized"},...(result[3].rows as any[]).map(item=>({id:String(item.id),name:String(item.name)}))],pagination:{page:options.page,limit:options.limit,total:number(row(result[0]).total),pages:Math.max(1,Math.ceil(number(row(result[0]).total)/options.limit))}};
	}

	static async productTrend(storeId:string,productId:string,input:ReportPeriodInput){await this.ensureIndexes();const db=DbConn.getClient(),periods=await this.periods(storeId,input),current=this.clauses(storeId,periods.current),modifier=`${input.timezoneOffset>=0?"+":""}${input.timezoneOffset} minutes`,mode=bucketMode(periods.current.days),expr=mode==="hour"?`strftime('%H:00',o.paid_at,'${modifier}')`:mode==="day"?`strftime('%Y-%m-%d',o.paid_at,'${modifier}')`:`date(o.paid_at,'${modifier}','-' || ((strftime('%w',o.paid_at,'${modifier}')+6)%7) || ' days')`;const result=await db.execute({sql:`SELECT ${expr} label,COALESCE(SUM(oi.qty_base),0) quantity,COALESCE(SUM(oi.line_total),0) revenue FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE ${current.paid} AND oi.product_id=? AND COALESCE(oi.line_status,'sent')!='cancelled' AND COALESCE(oi.is_gift,0)=0 GROUP BY label ORDER BY label`,args:[...current.args,productId]});return{period:periods.current,items:result.rows.map((item:any)=>({label:String(item.label),quantity:number(item.quantity),revenue:number(item.revenue)}))};}
}
