/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const AUDITEVENT_TABLE = "audit_events";
export const AUDITEVENT_COLUMNS = ["id", "scope", "store_id", "actor_user_id", "actor_name", "actor_role", "action", "entity_type", "entity_id", "result", "reason_code", "ip_address", "user_agent", "request_id", "metadata", "before", "after", "occurred_at"] as const;
export const AUDITEVENT_PRIMARY_KEYS = ["id"] as const;

export type AuditEventRow = {
	id: string;
	scope: string;
	store_id: string | null;
	actor_user_id: string | null;
	actor_name: string | null;
	actor_role: string | null;
	action: string;
	entity_type: string;
	entity_id: string | null;
	result: string;
	reason_code: string | null;
	ip_address: string | null;
	user_agent: string | null;
	request_id: string | null;
	metadata: string | null;
	before: string | null;
	after: string | null;
	occurred_at: string;
};

export type AuditEventCreateInput = {
	id?: string;
	scope: string;
	store_id?: string | null;
	actor_user_id?: string | null;
	actor_name?: string | null;
	actor_role?: string | null;
	action: string;
	entity_type: string;
	entity_id?: string | null;
	result?: string;
	reason_code?: string | null;
	ip_address?: string | null;
	user_agent?: string | null;
	request_id?: string | null;
	metadata?: string | null;
	before?: string | null;
	after?: string | null;
	occurred_at?: string;
};

export type AuditEventUpdateInput = {
	scope?: string;
	store_id?: string | null;
	actor_user_id?: string | null;
	actor_name?: string | null;
	actor_role?: string | null;
	action?: string;
	entity_type?: string;
	entity_id?: string | null;
	result?: string;
	reason_code?: string | null;
	ip_address?: string | null;
	user_agent?: string | null;
	request_id?: string | null;
	metadata?: string | null;
	before?: string | null;
	after?: string | null;
	occurred_at?: string;
};

export type AuditEvent = AuditEventRow;
export type CreateAuditEventInput = AuditEventCreateInput;
export type UpdateAuditEventInput = AuditEventUpdateInput;
