/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const CASHFLOWENTRY_TABLE = "cash_flow_entries";
export const CASHFLOWENTRY_COLUMNS = ["id", "store_id", "account_id", "direction", "entry_type", "source_type", "source_id", "amount", "currency", "reference", "note", "metadata", "occurred_at", "created_by", "created_at"] as const;
export const CASHFLOWENTRY_PRIMARY_KEYS = ["id"] as const;

export type CashFlowEntryRow = {
	id: string;
	store_id: string;
	account_id: string | null;
	direction: string;
	entry_type: string;
	source_type: string;
	source_id: string;
	amount: number;
	currency: string;
	reference: string | null;
	note: string | null;
	metadata: string;
	occurred_at: string;
	created_by: string | null;
	created_at: string;
};

export type CashFlowEntryCreateInput = {
	id?: string;
	store_id: string;
	account_id?: string | null;
	direction: string;
	entry_type: string;
	source_type: string;
	source_id: string;
	amount: number;
	currency?: string;
	reference?: string | null;
	note?: string | null;
	metadata?: string;
	occurred_at?: string;
	created_by?: string | null;
	created_at?: string;
};

export type CashFlowEntryUpdateInput = {
	store_id?: string;
	account_id?: string | null;
	direction?: string;
	entry_type?: string;
	source_type?: string;
	source_id?: string;
	amount?: number;
	currency?: string;
	reference?: string | null;
	note?: string | null;
	metadata?: string;
	occurred_at?: string;
	created_by?: string | null;
	created_at?: string;
};

export type CashFlowEntry = CashFlowEntryRow;
export type CreateCashFlowEntryInput = CashFlowEntryCreateInput;
export type UpdateCashFlowEntryInput = CashFlowEntryUpdateInput;
