/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const CONTACT_TABLE = "contacts";
export const CONTACT_COLUMNS = ["id", "store_id", "channel", "display_name", "phone", "last_inbound_at", "notes", "created_at"] as const;
export const CONTACT_PRIMARY_KEYS = ["id"] as const;

export type ContactRow = {
	id: string;
	store_id: string;
	channel: string;
	display_name: string;
	phone: string | null;
	last_inbound_at: string | null;
	notes: string | null;
	created_at: string;
};

export type ContactCreateInput = {
	id?: string;
	store_id: string;
	channel: string;
	display_name: string;
	phone?: string | null;
	last_inbound_at?: string | null;
	notes?: string | null;
	created_at?: string;
};

export type ContactUpdateInput = {
	store_id?: string;
	channel?: string;
	display_name?: string;
	phone?: string | null;
	last_inbound_at?: string | null;
	notes?: string | null;
	created_at?: string;
};

export type Contact = ContactRow;
export type CreateContactInput = ContactCreateInput;
export type UpdateContactInput = ContactUpdateInput;
