/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const DRIZZLEMIGRATION_TABLE = "__drizzle_migrations";
export const DRIZZLEMIGRATION_COLUMNS = ["id", "hash", "created_at"] as const;
export const DRIZZLEMIGRATION_PRIMARY_KEYS = ["id"] as const;

export type DrizzleMigrationRow = {
	id: number;
	hash: string;
	created_at: number | null;
};

export type DrizzleMigrationCreateInput = {
	id?: number;
	hash: string;
	created_at?: number | null;
};

export type DrizzleMigrationUpdateInput = {
	hash?: string;
	created_at?: number | null;
};

export type DrizzleMigration = DrizzleMigrationRow;
export type CreateDrizzleMigrationInput = DrizzleMigrationCreateInput;
export type UpdateDrizzleMigrationInput = DrizzleMigrationUpdateInput;
