/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const FBCONNECTION_TABLE = "fb_connections";
export const FBCONNECTION_COLUMNS = ["id", "store_id", "status", "page_name", "page_id", "connected_at"] as const;
export const FBCONNECTION_PRIMARY_KEYS = ["id"] as const;

export type FbConnectionRow = {
	id: string;
	store_id: string;
	status: string;
	page_name: string | null;
	page_id: string | null;
	connected_at: string | null;
};

export type FbConnectionCreateInput = {
	id?: string;
	store_id: string;
	status?: string;
	page_name?: string | null;
	page_id?: string | null;
	connected_at?: string | null;
};

export type FbConnectionUpdateInput = {
	store_id?: string;
	status?: string;
	page_name?: string | null;
	page_id?: string | null;
	connected_at?: string | null;
};

export type FbConnection = FbConnectionRow;
export type CreateFbConnectionInput = FbConnectionCreateInput;
export type UpdateFbConnectionInput = FbConnectionUpdateInput;
