/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const FINANCIALACCOUNT_TABLE = "financial_accounts";
export const FINANCIALACCOUNT_COLUMNS = ["id", "store_id", "display_name", "account_type", "store_payment_account_id", "is_system", "is_active", "created_at", "updated_at"] as const;
export const FINANCIALACCOUNT_PRIMARY_KEYS = ["id"] as const;

export type FinancialAccountRow = {
	id: string;
	store_id: string;
	display_name: string;
	account_type: string;
	store_payment_account_id: string | null;
	is_system: number;
	is_active: number;
	created_at: string;
	updated_at: string;
};

export type FinancialAccountCreateInput = {
	id?: string;
	store_id: string;
	display_name: string;
	account_type: string;
	store_payment_account_id?: string | null;
	is_system?: number;
	is_active?: number;
	created_at?: string;
	updated_at?: string;
};

export type FinancialAccountUpdateInput = {
	store_id?: string;
	display_name?: string;
	account_type?: string;
	store_payment_account_id?: string | null;
	is_system?: number;
	is_active?: number;
	created_at?: string;
	updated_at?: string;
};

export type FinancialAccount = FinancialAccountRow;
export type CreateFinancialAccountInput = FinancialAccountCreateInput;
export type UpdateFinancialAccountInput = FinancialAccountUpdateInput;
