/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const IDEMPOTENCYREQUEST_TABLE = "idempotency_requests";
export const IDEMPOTENCYREQUEST_COLUMNS = ["id", "store_id", "action", "idempotency_key", "request_hash", "status", "response_status", "response_body", "created_by", "created_at", "completed_at"] as const;
export const IDEMPOTENCYREQUEST_PRIMARY_KEYS = ["id"] as const;

export type IdempotencyRequestRow = {
	id: string;
	store_id: string;
	action: string;
	idempotency_key: string;
	request_hash: string;
	status: string;
	response_status: number | null;
	response_body: string | null;
	created_by: string | null;
	created_at: string;
	completed_at: string | null;
};

export type IdempotencyRequestCreateInput = {
	id?: string;
	store_id: string;
	action: string;
	idempotency_key: string;
	request_hash: string;
	status?: string;
	response_status?: number | null;
	response_body?: string | null;
	created_by?: string | null;
	created_at?: string;
	completed_at?: string | null;
};

export type IdempotencyRequestUpdateInput = {
	store_id?: string;
	action?: string;
	idempotency_key?: string;
	request_hash?: string;
	status?: string;
	response_status?: number | null;
	response_body?: string | null;
	created_by?: string | null;
	created_at?: string;
	completed_at?: string | null;
};

export type IdempotencyRequest = IdempotencyRequestRow;
export type CreateIdempotencyRequestInput = IdempotencyRequestCreateInput;
export type UpdateIdempotencyRequestInput = IdempotencyRequestUpdateInput;
