/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const INVENTORYMOVEMENT_TABLE = "inventory_movements";
export const INVENTORYMOVEMENT_COLUMNS = ["id", "store_id", "product_id", "type", "qty_base", "ref_type", "ref_id", "note", "created_by", "created_at"] as const;
export const INVENTORYMOVEMENT_PRIMARY_KEYS = ["id"] as const;

export type InventoryMovementRow = {
	id: string;
	store_id: string;
	product_id: string;
	type: string;
	qty_base: number;
	ref_type: string;
	ref_id: string | null;
	note: string | null;
	created_by: string | null;
	created_at: string;
};

export type InventoryMovementCreateInput = {
	id?: string;
	store_id: string;
	product_id: string;
	type: string;
	qty_base: number;
	ref_type: string;
	ref_id?: string | null;
	note?: string | null;
	created_by?: string | null;
	created_at?: string;
};

export type InventoryMovementUpdateInput = {
	store_id?: string;
	product_id?: string;
	type?: string;
	qty_base?: number;
	ref_type?: string;
	ref_id?: string | null;
	note?: string | null;
	created_by?: string | null;
	created_at?: string;
};

export type InventoryMovement = InventoryMovementRow;
export type CreateInventoryMovementInput = InventoryMovementCreateInput;
export type UpdateInventoryMovementInput = InventoryMovementUpdateInput;
