/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const INVENTORYBALANCE_TABLE = "inventory_balances";
export const INVENTORYBALANCE_COLUMNS = ["store_id", "product_id", "on_hand_base", "reserved_base", "available_base", "updated_at"] as const;
export const INVENTORYBALANCE_PRIMARY_KEYS = ["store_id", "product_id"] as const;

export type InventoryBalanceRow = {
	store_id: string;
	product_id: string;
	on_hand_base: number;
	reserved_base: number;
	available_base: number;
	updated_at: string;
};

export type InventoryBalanceCreateInput = {
	store_id?: string;
	product_id?: string;
	on_hand_base?: number;
	reserved_base?: number;
	available_base?: number;
	updated_at?: string;
};

export type InventoryBalanceUpdateInput = {
	on_hand_base?: number;
	reserved_base?: number;
	available_base?: number;
	updated_at?: string;
};

export type InventoryBalance = InventoryBalanceRow;
export type CreateInventoryBalanceInput = InventoryBalanceCreateInput;
export type UpdateInventoryBalanceInput = InventoryBalanceUpdateInput;
