/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const NOTIFICATIONRULE_TABLE = "notification_rules";
export const NOTIFICATIONRULE_COLUMNS = ["id", "store_id", "topic", "entity_type", "entity_id", "muted_forever", "muted_until", "snoozed_until", "note", "updated_by", "created_at", "updated_at"] as const;
export const NOTIFICATIONRULE_PRIMARY_KEYS = ["id"] as const;

export type NotificationRuleRow = {
	id: string;
	store_id: string;
	topic: string;
	entity_type: string;
	entity_id: string;
	muted_forever: number;
	muted_until: string | null;
	snoozed_until: string | null;
	note: string | null;
	updated_by: string | null;
	created_at: string;
	updated_at: string;
};

export type NotificationRuleCreateInput = {
	id?: string;
	store_id: string;
	topic?: string;
	entity_type: string;
	entity_id: string;
	muted_forever?: number;
	muted_until?: string | null;
	snoozed_until?: string | null;
	note?: string | null;
	updated_by?: string | null;
	created_at?: string;
	updated_at?: string;
};

export type NotificationRuleUpdateInput = {
	store_id?: string;
	topic?: string;
	entity_type?: string;
	entity_id?: string;
	muted_forever?: number;
	muted_until?: string | null;
	snoozed_until?: string | null;
	note?: string | null;
	updated_by?: string | null;
	created_at?: string;
	updated_at?: string;
};

export type NotificationRule = NotificationRuleRow;
export type CreateNotificationRuleInput = NotificationRuleCreateInput;
export type UpdateNotificationRuleInput = NotificationRuleUpdateInput;
