/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const NOTIFICATIONINBOX_TABLE = "notification_inbox";
export const NOTIFICATIONINBOX_COLUMNS = ["id", "store_id", "topic", "entity_type", "entity_id", "dedupe_key", "title", "message", "severity", "status", "due_status", "due_date", "payload", "first_detected_at", "last_detected_at", "read_at", "resolved_at", "created_at", "updated_at"] as const;
export const NOTIFICATIONINBOX_PRIMARY_KEYS = ["id"] as const;

export type NotificationInboxRow = {
	id: string;
	store_id: string;
	topic: string;
	entity_type: string;
	entity_id: string;
	dedupe_key: string;
	title: string;
	message: string;
	severity: string;
	status: string;
	due_status: string | null;
	due_date: string | null;
	payload: string;
	first_detected_at: string;
	last_detected_at: string;
	read_at: string | null;
	resolved_at: string | null;
	created_at: string;
	updated_at: string;
};

export type NotificationInboxCreateInput = {
	id?: string;
	store_id: string;
	topic?: string;
	entity_type: string;
	entity_id: string;
	dedupe_key: string;
	title: string;
	message: string;
	severity?: string;
	status?: string;
	due_status?: string | null;
	due_date?: string | null;
	payload?: string;
	first_detected_at?: string;
	last_detected_at?: string;
	read_at?: string | null;
	resolved_at?: string | null;
	created_at?: string;
	updated_at?: string;
};

export type NotificationInboxUpdateInput = {
	store_id?: string;
	topic?: string;
	entity_type?: string;
	entity_id?: string;
	dedupe_key?: string;
	title?: string;
	message?: string;
	severity?: string;
	status?: string;
	due_status?: string | null;
	due_date?: string | null;
	payload?: string;
	first_detected_at?: string;
	last_detected_at?: string;
	read_at?: string | null;
	resolved_at?: string | null;
	created_at?: string;
	updated_at?: string;
};

export type NotificationInbox = NotificationInboxRow;
export type CreateNotificationInboxInput = NotificationInboxCreateInput;
export type UpdateNotificationInboxInput = NotificationInboxUpdateInput;
