/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const ORDERITEM_TABLE = "order_items";
export const ORDERITEM_COLUMNS = ["id", "order_id", "product_id", "unit_id", "qty", "qty_base", "price_base_at_sale", "cost_base_at_sale", "line_total"] as const;
export const ORDERITEM_PRIMARY_KEYS = ["id"] as const;

export type OrderItemRow = {
	id: string;
	order_id: string;
	product_id: string;
	unit_id: string;
	qty: number;
	qty_base: number;
	price_base_at_sale: number;
	cost_base_at_sale: number;
	line_total: number;
};

export type OrderItemCreateInput = {
	id?: string;
	order_id: string;
	product_id: string;
	unit_id: string;
	qty: number;
	qty_base: number;
	price_base_at_sale: number;
	cost_base_at_sale: number;
	line_total: number;
};

export type OrderItemUpdateInput = {
	order_id?: string;
	product_id?: string;
	unit_id?: string;
	qty?: number;
	qty_base?: number;
	price_base_at_sale?: number;
	cost_base_at_sale?: number;
	line_total?: number;
};

export type OrderItem = OrderItemRow;
export type CreateOrderItemInput = OrderItemCreateInput;
export type UpdateOrderItemInput = OrderItemUpdateInput;
