/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const ORDERSHIPMENT_TABLE = "order_shipments";
export const ORDERSHIPMENT_COLUMNS = ["id", "order_id", "store_id", "provider", "status", "tracking_no", "label_url", "label_file_key", "provider_request_id", "provider_response", "last_error", "created_by", "created_at", "updated_at"] as const;
export const ORDERSHIPMENT_PRIMARY_KEYS = ["id"] as const;

export type OrderShipmentRow = {
	id: string;
	order_id: string;
	store_id: string;
	provider: string;
	status: string;
	tracking_no: string | null;
	label_url: string | null;
	label_file_key: string | null;
	provider_request_id: string | null;
	provider_response: string | null;
	last_error: string | null;
	created_by: string | null;
	created_at: string;
	updated_at: string;
};

export type OrderShipmentCreateInput = {
	id?: string;
	order_id: string;
	store_id: string;
	provider: string;
	status?: string;
	tracking_no?: string | null;
	label_url?: string | null;
	label_file_key?: string | null;
	provider_request_id?: string | null;
	provider_response?: string | null;
	last_error?: string | null;
	created_by?: string | null;
	created_at?: string;
	updated_at?: string;
};

export type OrderShipmentUpdateInput = {
	order_id?: string;
	store_id?: string;
	provider?: string;
	status?: string;
	tracking_no?: string | null;
	label_url?: string | null;
	label_file_key?: string | null;
	provider_request_id?: string | null;
	provider_response?: string | null;
	last_error?: string | null;
	created_by?: string | null;
	created_at?: string;
	updated_at?: string;
};

export type OrderShipment = OrderShipmentRow;
export type CreateOrderShipmentInput = OrderShipmentCreateInput;
export type UpdateOrderShipmentInput = OrderShipmentUpdateInput;
