/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const PERMISSION_TABLE = "permissions";
export const PERMISSION_COLUMNS = ["id", "key", "resource", "action"] as const;
export const PERMISSION_PRIMARY_KEYS = ["id"] as const;

export type PermissionRow = {
	id: string;
	key: string;
	resource: string;
	action: string;
};

export type PermissionCreateInput = {
	id?: string;
	key: string;
	resource: string;
	action: string;
};

export type PermissionUpdateInput = {
	key?: string;
	resource?: string;
	action?: string;
};

export type Permission = PermissionRow;
export type CreatePermissionInput = PermissionCreateInput;
export type UpdatePermissionInput = PermissionUpdateInput;
