/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const PRODUCTMODEL_TABLE = "product_models";
export const PRODUCTMODEL_COLUMNS = ["id", "store_id", "name", "category_id", "image_url", "description", "active", "created_at"] as const;
export const PRODUCTMODEL_PRIMARY_KEYS = ["id"] as const;

export type ProductModelRow = {
	id: string;
	store_id: string;
	name: string;
	category_id: string | null;
	image_url: string | null;
	description: string | null;
	active: number;
	created_at: string;
};

export type ProductModelCreateInput = {
	id?: string;
	store_id: string;
	name: string;
	category_id?: string | null;
	image_url?: string | null;
	description?: string | null;
	active?: number;
	created_at?: string;
};

export type ProductModelUpdateInput = {
	store_id?: string;
	name?: string;
	category_id?: string | null;
	image_url?: string | null;
	description?: string | null;
	active?: number;
	created_at?: string;
};

export type ProductModel = ProductModelRow;
export type CreateProductModelInput = ProductModelCreateInput;
export type UpdateProductModelInput = ProductModelUpdateInput;
