/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const PRODUCTUNIT_TABLE = "product_units";
export const PRODUCTUNIT_COLUMNS = ["id", "product_id", "unit_id", "multiplier_to_base", "price_per_unit", "enabled_for_sale"] as const;
export const PRODUCTUNIT_PRIMARY_KEYS = ["id"] as const;

export type ProductUnitRow = {
	id: string;
	product_id: string;
	unit_id: string;
	multiplier_to_base: number;
	price_per_unit: number | null;
	enabled_for_sale: number;
};

export type ProductUnitCreateInput = {
	id?: string;
	product_id: string;
	unit_id: string;
	multiplier_to_base: number;
	price_per_unit?: number | null;
	enabled_for_sale?: number;
};

export type ProductUnitUpdateInput = {
	product_id?: string;
	unit_id?: string;
	multiplier_to_base?: number;
	price_per_unit?: number | null;
	enabled_for_sale?: number;
};

export type ProductUnit = ProductUnitRow;
export type CreateProductUnitInput = ProductUnitCreateInput;
export type UpdateProductUnitInput = ProductUnitUpdateInput;
