/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const PRODUCTMODELATTRIBUTEVALUE_TABLE = "product_model_attribute_values";
export const PRODUCTMODELATTRIBUTEVALUE_COLUMNS = ["id", "attribute_id", "code", "name", "sort_order", "created_at"] as const;
export const PRODUCTMODELATTRIBUTEVALUE_PRIMARY_KEYS = ["id"] as const;

export type ProductModelAttributeValueRow = {
	id: string;
	attribute_id: string;
	code: string;
	name: string;
	sort_order: number;
	created_at: string;
};

export type ProductModelAttributeValueCreateInput = {
	id?: string;
	attribute_id: string;
	code: string;
	name: string;
	sort_order?: number;
	created_at?: string;
};

export type ProductModelAttributeValueUpdateInput = {
	attribute_id?: string;
	code?: string;
	name?: string;
	sort_order?: number;
	created_at?: string;
};

export type ProductModelAttributeValue = ProductModelAttributeValueRow;
export type CreateProductModelAttributeValueInput = ProductModelAttributeValueCreateInput;
export type UpdateProductModelAttributeValueInput = ProductModelAttributeValueUpdateInput;
