/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const PRODUCTCATEGORY_TABLE = "product_categories";
export const PRODUCTCATEGORY_COLUMNS = ["id", "store_id", "name", "sort_order", "created_at"] as const;
export const PRODUCTCATEGORY_PRIMARY_KEYS = ["id"] as const;

export type ProductCategoryRow = {
	id: string;
	store_id: string;
	name: string;
	sort_order: number;
	created_at: string;
};

export type ProductCategoryCreateInput = {
	id?: string;
	store_id: string;
	name: string;
	sort_order?: number;
	created_at?: string;
};

export type ProductCategoryUpdateInput = {
	store_id?: string;
	name?: string;
	sort_order?: number;
	created_at?: string;
};

export type ProductCategory = ProductCategoryRow;
export type CreateProductCategoryInput = ProductCategoryCreateInput;
export type UpdateProductCategoryInput = ProductCategoryUpdateInput;
