/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const PRODUCTMODELATTRIBUTE_TABLE = "product_model_attributes";
export const PRODUCTMODELATTRIBUTE_COLUMNS = ["id", "model_id", "code", "name", "sort_order", "created_at"] as const;
export const PRODUCTMODELATTRIBUTE_PRIMARY_KEYS = ["id"] as const;

export type ProductModelAttributeRow = {
	id: string;
	model_id: string;
	code: string;
	name: string;
	sort_order: number;
	created_at: string;
};

export type ProductModelAttributeCreateInput = {
	id?: string;
	model_id: string;
	code: string;
	name: string;
	sort_order?: number;
	created_at?: string;
};

export type ProductModelAttributeUpdateInput = {
	model_id?: string;
	code?: string;
	name?: string;
	sort_order?: number;
	created_at?: string;
};

export type ProductModelAttribute = ProductModelAttributeRow;
export type CreateProductModelAttributeInput = ProductModelAttributeCreateInput;
export type UpdateProductModelAttributeInput = ProductModelAttributeUpdateInput;
