/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const PRODUCT_TABLE = "products";
export const PRODUCT_COLUMNS = ["id", "store_id", "sku", "name", "barcode", "base_unit_id", "price_base", "cost_base", "active", "created_at", "image_url", "category_id", "out_stock_threshold", "low_stock_threshold", "model_id", "variant_label", "variant_options_json", "variant_sort_order", "allow_base_unit_sale", "location"] as const;
export const PRODUCT_PRIMARY_KEYS = ["id"] as const;

export type ProductRow = {
	id: string;
	store_id: string;
	sku: string;
	name: string;
	barcode: string | null;
	base_unit_id: string;
	price_base: number;
	cost_base: number;
	active: number;
	created_at: string;
	image_url: string | null;
	category_id: string | null;
	out_stock_threshold: number | null;
	low_stock_threshold: number | null;
	model_id: string | null;
	variant_label: string | null;
	variant_options_json: string | null;
	variant_sort_order: number;
	allow_base_unit_sale: number;
	location: string | null;
};

export type ProductCreateInput = {
	id?: string;
	store_id: string;
	sku: string;
	name: string;
	barcode?: string | null;
	base_unit_id: string;
	price_base: number;
	cost_base: number;
	active?: number;
	created_at?: string;
	image_url?: string | null;
	category_id?: string | null;
	out_stock_threshold?: number | null;
	low_stock_threshold?: number | null;
	model_id?: string | null;
	variant_label?: string | null;
	variant_options_json?: string | null;
	variant_sort_order?: number;
	allow_base_unit_sale?: number;
	location?: string | null;
};

export type ProductUpdateInput = {
	store_id?: string;
	sku?: string;
	name?: string;
	barcode?: string | null;
	base_unit_id?: string;
	price_base?: number;
	cost_base?: number;
	active?: number;
	created_at?: string;
	image_url?: string | null;
	category_id?: string | null;
	out_stock_threshold?: number | null;
	low_stock_threshold?: number | null;
	model_id?: string | null;
	variant_label?: string | null;
	variant_options_json?: string | null;
	variant_sort_order?: number;
	allow_base_unit_sale?: number;
	location?: string | null;
};

export type Product = ProductRow;
export type CreateProductInput = ProductCreateInput;
export type UpdateProductInput = ProductUpdateInput;
