/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const PURCHASEORDERPAYMENT_TABLE = "purchase_order_payments";
export const PURCHASEORDERPAYMENT_COLUMNS = ["id", "purchase_order_id", "store_id", "entry_type", "amount_base", "paid_at", "reference", "note", "reversed_payment_id", "created_by", "created_at"] as const;
export const PURCHASEORDERPAYMENT_PRIMARY_KEYS = ["id"] as const;

export type PurchaseOrderPaymentRow = {
	id: string;
	purchase_order_id: string;
	store_id: string;
	entry_type: string;
	amount_base: number;
	paid_at: string;
	reference: string | null;
	note: string | null;
	reversed_payment_id: string | null;
	created_by: string | null;
	created_at: string;
};

export type PurchaseOrderPaymentCreateInput = {
	id?: string;
	purchase_order_id: string;
	store_id: string;
	entry_type?: string;
	amount_base: number;
	paid_at?: string;
	reference?: string | null;
	note?: string | null;
	reversed_payment_id?: string | null;
	created_by?: string | null;
	created_at?: string;
};

export type PurchaseOrderPaymentUpdateInput = {
	purchase_order_id?: string;
	store_id?: string;
	entry_type?: string;
	amount_base?: number;
	paid_at?: string;
	reference?: string | null;
	note?: string | null;
	reversed_payment_id?: string | null;
	created_by?: string | null;
	created_at?: string;
};

export type PurchaseOrderPayment = PurchaseOrderPaymentRow;
export type CreatePurchaseOrderPaymentInput = PurchaseOrderPaymentCreateInput;
export type UpdatePurchaseOrderPaymentInput = PurchaseOrderPaymentUpdateInput;
