/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const PURCHASEORDERITEM_TABLE = "purchase_order_items";
export const PURCHASEORDERITEM_COLUMNS = ["id", "purchase_order_id", "product_id", "qty_ordered", "qty_received", "unit_cost_purchase", "unit_cost_base", "landed_cost_per_unit", "unit_id", "multiplier_to_base", "qty_base_ordered", "qty_base_received"] as const;
export const PURCHASEORDERITEM_PRIMARY_KEYS = ["id"] as const;

export type PurchaseOrderItemRow = {
	id: string;
	purchase_order_id: string;
	product_id: string;
	qty_ordered: number;
	qty_received: number;
	unit_cost_purchase: number;
	unit_cost_base: number;
	landed_cost_per_unit: number;
	unit_id: string | null;
	multiplier_to_base: number;
	qty_base_ordered: number;
	qty_base_received: number;
};

export type PurchaseOrderItemCreateInput = {
	id?: string;
	purchase_order_id: string;
	product_id: string;
	qty_ordered: number;
	qty_received?: number;
	unit_cost_purchase?: number;
	unit_cost_base?: number;
	landed_cost_per_unit?: number;
	unit_id?: string | null;
	multiplier_to_base?: number;
	qty_base_ordered?: number;
	qty_base_received?: number;
};

export type PurchaseOrderItemUpdateInput = {
	purchase_order_id?: string;
	product_id?: string;
	qty_ordered?: number;
	qty_received?: number;
	unit_cost_purchase?: number;
	unit_cost_base?: number;
	landed_cost_per_unit?: number;
	unit_id?: string | null;
	multiplier_to_base?: number;
	qty_base_ordered?: number;
	qty_base_received?: number;
};

export type PurchaseOrderItem = PurchaseOrderItemRow;
export type CreatePurchaseOrderItemInput = PurchaseOrderItemCreateInput;
export type UpdatePurchaseOrderItemInput = PurchaseOrderItemUpdateInput;
