/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const ROLE_TABLE = "roles";
export const ROLE_COLUMNS = ["id", "store_id", "name", "is_system", "created_at", "deleted_at"] as const;
export const ROLE_PRIMARY_KEYS = ["id"] as const;

export type RoleRow = {
	id: string;
	store_id: string;
	name: string;
	is_system: number;
	created_at: string;
	deleted_at: string | null;
};

export type RoleCreateInput = {
	id?: string;
	store_id: string;
	name: string;
	is_system?: number;
	created_at?: string;
	deleted_at?: string | null;
};

export type RoleUpdateInput = {
	store_id?: string;
	name?: string;
	is_system?: number;
	created_at?: string;
	deleted_at?: string | null;
};

export type Role = RoleRow;
export type CreateRoleInput = RoleCreateInput;
export type UpdateRoleInput = RoleUpdateInput;
