/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const ROLEPERMISSION_TABLE = "role_permissions";
export const ROLEPERMISSION_COLUMNS = ["role_id", "permission_id"] as const;
export const ROLEPERMISSION_PRIMARY_KEYS = ["role_id", "permission_id"] as const;

export type RolePermissionRow = {
	role_id: string;
	permission_id: string;
};

export type RolePermissionCreateInput = {
	role_id?: string;
	permission_id?: string;
};

export type RolePermissionUpdateInput = {
	[key: string]: never;
};

export type RolePermission = RolePermissionRow;
export type CreateRolePermissionInput = RolePermissionCreateInput;
export type UpdateRolePermissionInput = RolePermissionUpdateInput;
