/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const SHIPPINGPROVIDER_TABLE = "shipping_providers";
export const SHIPPINGPROVIDER_COLUMNS = ["id", "store_id", "code", "display_name", "branch_name", "aliases", "active", "sort_order", "created_at"] as const;
export const SHIPPINGPROVIDER_PRIMARY_KEYS = ["id"] as const;

export type ShippingProviderRow = {
	id: string;
	store_id: string;
	code: string;
	display_name: string;
	branch_name: string | null;
	aliases: string;
	active: number;
	sort_order: number;
	created_at: string;
};

export type ShippingProviderCreateInput = {
	id?: string;
	store_id: string;
	code: string;
	display_name: string;
	branch_name?: string | null;
	aliases?: string;
	active?: number;
	sort_order?: number;
	created_at?: string;
};

export type ShippingProviderUpdateInput = {
	store_id?: string;
	code?: string;
	display_name?: string;
	branch_name?: string | null;
	aliases?: string;
	active?: number;
	sort_order?: number;
	created_at?: string;
};

export type ShippingProvider = ShippingProviderRow;
export type CreateShippingProviderInput = ShippingProviderCreateInput;
export type UpdateShippingProviderInput = ShippingProviderUpdateInput;
