/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const STOREBRANCH_TABLE = "store_branches";
export const STOREBRANCH_COLUMNS = ["id", "store_id", "name", "code", "address", "created_at", "source_branch_id", "sharing_mode", "sharing_config"] as const;
export const STOREBRANCH_PRIMARY_KEYS = ["id"] as const;

export type StoreBranchRow = {
	id: string;
	store_id: string;
	name: string;
	code: string | null;
	address: string | null;
	created_at: string;
	source_branch_id: string | null;
	sharing_mode: string | null;
	sharing_config: string | null;
};

export type StoreBranchCreateInput = {
	id?: string;
	store_id: string;
	name: string;
	code?: string | null;
	address?: string | null;
	created_at?: string;
	source_branch_id?: string | null;
	sharing_mode?: string | null;
	sharing_config?: string | null;
};

export type StoreBranchUpdateInput = {
	store_id?: string;
	name?: string;
	code?: string | null;
	address?: string | null;
	created_at?: string;
	source_branch_id?: string | null;
	sharing_mode?: string | null;
	sharing_config?: string | null;
};

export type StoreBranch = StoreBranchRow;
export type CreateStoreBranchInput = StoreBranchCreateInput;
export type UpdateStoreBranchInput = StoreBranchUpdateInput;
