/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const STOREINTEGRATION_TABLE = "store_integrations";
export const STOREINTEGRATION_COLUMNS = ["id", "store_id", "provider_type", "provider_name", "username_encrypted", "password_encrypted", "access_token_encrypted", "refresh_token_encrypted", "token_expires_at", "metadata_json", "created_at", "updated_at"] as const;
export const STOREINTEGRATION_PRIMARY_KEYS = ["id"] as const;

export type StoreIntegrationRow = {
	id: string;
	store_id: string;
	provider_type: string;
	provider_name: string;
	username_encrypted: string | null;
	password_encrypted: string | null;
	access_token_encrypted: string | null;
	refresh_token_encrypted: string | null;
	token_expires_at: string | null;
	metadata_json: string | null;
	created_at: string;
	updated_at: string;
};

export type StoreIntegrationCreateInput = {
	id?: string;
	store_id: string;
	provider_type: string;
	provider_name: string;
	username_encrypted?: string | null;
	password_encrypted?: string | null;
	access_token_encrypted?: string | null;
	refresh_token_encrypted?: string | null;
	token_expires_at?: string | null;
	metadata_json?: string | null;
	created_at?: string;
	updated_at?: string;
};

export type StoreIntegrationUpdateInput = {
	store_id?: string;
	provider_type?: string;
	provider_name?: string;
	username_encrypted?: string | null;
	password_encrypted?: string | null;
	access_token_encrypted?: string | null;
	refresh_token_encrypted?: string | null;
	token_expires_at?: string | null;
	metadata_json?: string | null;
	created_at?: string;
	updated_at?: string;
};

export type StoreIntegration = StoreIntegrationRow;
export type CreateStoreIntegrationInput = StoreIntegrationCreateInput;
export type UpdateStoreIntegrationInput = StoreIntegrationUpdateInput;
