/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const STOREPAYMENTACCOUNT_TABLE = "store_payment_accounts";
export const STOREPAYMENTACCOUNT_COLUMNS = ["id", "store_id", "display_name", "account_type", "bank_name", "account_name", "account_number", "promptpay_id", "is_default", "is_active", "created_at", "updated_at", "qr_image_url", "currency"] as const;
export const STOREPAYMENTACCOUNT_PRIMARY_KEYS = ["id"] as const;

export type StorePaymentAccountRow = {
	id: string;
	store_id: string;
	display_name: string;
	account_type: string;
	bank_name: string | null;
	account_name: string;
	account_number: string | null;
	promptpay_id: string | null;
	is_default: number;
	is_active: number;
	created_at: string;
	updated_at: string;
	qr_image_url: string | null;
	currency: string;
};

export type StorePaymentAccountCreateInput = {
	id?: string;
	store_id: string;
	display_name: string;
	account_type: string;
	bank_name?: string | null;
	account_name: string;
	account_number?: string | null;
	promptpay_id?: string | null;
	is_default?: number;
	is_active?: number;
	created_at?: string;
	updated_at?: string;
	qr_image_url?: string | null;
	currency?: string;
};

export type StorePaymentAccountUpdateInput = {
	store_id?: string;
	display_name?: string;
	account_type?: string;
	bank_name?: string | null;
	account_name?: string;
	account_number?: string | null;
	promptpay_id?: string | null;
	is_default?: number;
	is_active?: number;
	created_at?: string;
	updated_at?: string;
	qr_image_url?: string | null;
	currency?: string;
};

export type StorePaymentAccount = StorePaymentAccountRow;
export type CreateStorePaymentAccountInput = StorePaymentAccountCreateInput;
export type UpdateStorePaymentAccountInput = StorePaymentAccountUpdateInput;
