/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const STORETYPETEMPLATE_TABLE = "store_type_templates";
export const STORETYPETEMPLATE_COLUMNS = ["store_type", "app_layout", "display_name", "description", "created_at", "updated_at"] as const;
export const STORETYPETEMPLATE_PRIMARY_KEYS = ["store_type"] as const;

export type StoreTypeTemplateRow = {
	store_type: string;
	app_layout: string;
	display_name: string;
	description: string;
	created_at: string;
	updated_at: string;
};

export type StoreTypeTemplateCreateInput = {
	store_type?: string;
	app_layout: string;
	display_name: string;
	description: string;
	created_at?: string;
	updated_at?: string;
};

export type StoreTypeTemplateUpdateInput = {
	app_layout?: string;
	display_name?: string;
	description?: string;
	created_at?: string;
	updated_at?: string;
};

export type StoreTypeTemplate = StoreTypeTemplateRow;
export type CreateStoreTypeTemplateInput = StoreTypeTemplateCreateInput;
export type UpdateStoreTypeTemplateInput = StoreTypeTemplateUpdateInput;
