/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const STOREMEMBERBRANCH_TABLE = "store_member_branches";
export const STOREMEMBERBRANCH_COLUMNS = ["store_id", "user_id", "branch_id", "created_at"] as const;
export const STOREMEMBERBRANCH_PRIMARY_KEYS = ["store_id", "user_id", "branch_id"] as const;

export type StoreMemberBranchRow = {
	store_id: string;
	user_id: string;
	branch_id: string;
	created_at: string;
};

export type StoreMemberBranchCreateInput = {
	store_id?: string;
	user_id?: string;
	branch_id?: string;
	created_at?: string;
};

export type StoreMemberBranchUpdateInput = {
	created_at?: string;
};

export type StoreMemberBranch = StoreMemberBranchRow;
export type CreateStoreMemberBranchInput = StoreMemberBranchCreateInput;
export type UpdateStoreMemberBranchInput = StoreMemberBranchUpdateInput;
