/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const STOREMEMBER_TABLE = "store_members";
export const STOREMEMBER_COLUMNS = ["store_id", "user_id", "role_id", "status", "created_at", "added_by"] as const;
export const STOREMEMBER_PRIMARY_KEYS = ["store_id", "user_id"] as const;

export type StoreMemberRow = {
	store_id: string;
	user_id: string;
	role_id: string;
	status: string;
	created_at: string;
	added_by: string | null;
};

export type StoreMemberCreateInput = {
	store_id?: string;
	user_id?: string;
	role_id: string;
	status?: string;
	created_at?: string;
	added_by?: string | null;
};

export type StoreMemberUpdateInput = {
	role_id?: string;
	status?: string;
	created_at?: string;
	added_by?: string | null;
};

export type StoreMember = StoreMemberRow;
export type CreateStoreMemberInput = StoreMemberCreateInput;
export type UpdateStoreMemberInput = StoreMemberUpdateInput;
