/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const STORE_TABLE = "stores";
export const STORE_COLUMNS = ["id", "name", "store_type", "currency", "vat_enabled", "vat_rate", "created_at", "max_branches_override", "logo_name", "logo_url", "address", "phone_number", "supported_currencies", "vat_mode", "out_stock_threshold", "low_stock_threshold", "pdf_show_logo", "pdf_show_signature", "pdf_show_note", "pdf_header_color", "pdf_company_name", "pdf_company_address", "pdf_company_phone"] as const;
export const STORE_PRIMARY_KEYS = ["id"] as const;

export type StoreRow = {
	id: string;
	name: string;
	store_type: string;
	currency: string;
	vat_enabled: number;
	vat_rate: number;
	created_at: string;
	max_branches_override: number | null;
	logo_name: string | null;
	logo_url: string | null;
	address: string | null;
	phone_number: string | null;
	supported_currencies: string;
	vat_mode: string;
	out_stock_threshold: number;
	low_stock_threshold: number;
	pdf_show_logo: number;
	pdf_show_signature: number;
	pdf_show_note: number;
	pdf_header_color: string;
	pdf_company_name: string | null;
	pdf_company_address: string | null;
	pdf_company_phone: string | null;
};

export type StoreCreateInput = {
	id?: string;
	name: string;
	store_type?: string;
	currency?: string;
	vat_enabled?: number;
	vat_rate?: number;
	created_at?: string;
	max_branches_override?: number | null;
	logo_name?: string | null;
	logo_url?: string | null;
	address?: string | null;
	phone_number?: string | null;
	supported_currencies?: string;
	vat_mode?: string;
	out_stock_threshold?: number;
	low_stock_threshold?: number;
	pdf_show_logo?: number;
	pdf_show_signature?: number;
	pdf_show_note?: number;
	pdf_header_color?: string;
	pdf_company_name?: string | null;
	pdf_company_address?: string | null;
	pdf_company_phone?: string | null;
};

export type StoreUpdateInput = {
	name?: string;
	store_type?: string;
	currency?: string;
	vat_enabled?: number;
	vat_rate?: number;
	created_at?: string;
	max_branches_override?: number | null;
	logo_name?: string | null;
	logo_url?: string | null;
	address?: string | null;
	phone_number?: string | null;
	supported_currencies?: string;
	vat_mode?: string;
	out_stock_threshold?: number;
	low_stock_threshold?: number;
	pdf_show_logo?: number;
	pdf_show_signature?: number;
	pdf_show_note?: number;
	pdf_header_color?: string;
	pdf_company_name?: string | null;
	pdf_company_address?: string | null;
	pdf_company_phone?: string | null;
};

export type Store = StoreRow;
export type CreateStoreInput = StoreCreateInput;
export type UpdateStoreInput = StoreUpdateInput;
