/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const SYSTEMCONFIG_TABLE = "system_config";
export const SYSTEMCONFIG_COLUMNS = ["id", "default_can_create_branches", "default_max_branches_per_store", "created_at", "updated_at", "default_session_limit", "store_logo_max_size_mb", "store_logo_auto_resize", "store_logo_resize_max_width", "payment_max_accounts_per_store", "payment_require_slip_for_lao_qr", "app_latest_build", "app_min_required_build", "app_update_message", "auth_access_token_ttl_minutes", "auth_refresh_token_ttl_days", "auth_remember_me_refresh_ttl_days", "auth_max_failed_attempts", "auth_lockout_minutes", "auth_allow_multi_session"] as const;
export const SYSTEMCONFIG_PRIMARY_KEYS = ["id"] as const;

export type SystemConfigRow = {
	id: string;
	default_can_create_branches: number;
	default_max_branches_per_store: number | null;
	created_at: string;
	updated_at: string;
	default_session_limit: number;
	store_logo_max_size_mb: number;
	store_logo_auto_resize: number;
	store_logo_resize_max_width: number;
	payment_max_accounts_per_store: number;
	payment_require_slip_for_lao_qr: number;
	app_latest_build: number;
	app_min_required_build: number;
	app_update_message: string | null;
	auth_access_token_ttl_minutes: number;
	auth_refresh_token_ttl_days: number;
	auth_remember_me_refresh_ttl_days: number;
	auth_max_failed_attempts: number;
	auth_lockout_minutes: number;
	auth_allow_multi_session: number;
};

export type SystemConfigCreateInput = {
	id?: string;
	default_can_create_branches?: number;
	default_max_branches_per_store?: number | null;
	created_at?: string;
	updated_at?: string;
	default_session_limit?: number;
	store_logo_max_size_mb?: number;
	store_logo_auto_resize?: number;
	store_logo_resize_max_width?: number;
	payment_max_accounts_per_store?: number;
	payment_require_slip_for_lao_qr?: number;
	app_latest_build?: number;
	app_min_required_build?: number;
	app_update_message?: string | null;
	auth_access_token_ttl_minutes?: number;
	auth_refresh_token_ttl_days?: number;
	auth_remember_me_refresh_ttl_days?: number;
	auth_max_failed_attempts?: number;
	auth_lockout_minutes?: number;
	auth_allow_multi_session?: number;
};

export type SystemConfigUpdateInput = {
	default_can_create_branches?: number;
	default_max_branches_per_store?: number | null;
	created_at?: string;
	updated_at?: string;
	default_session_limit?: number;
	store_logo_max_size_mb?: number;
	store_logo_auto_resize?: number;
	store_logo_resize_max_width?: number;
	payment_max_accounts_per_store?: number;
	payment_require_slip_for_lao_qr?: number;
	app_latest_build?: number;
	app_min_required_build?: number;
	app_update_message?: string | null;
	auth_access_token_ttl_minutes?: number;
	auth_refresh_token_ttl_days?: number;
	auth_remember_me_refresh_ttl_days?: number;
	auth_max_failed_attempts?: number;
	auth_lockout_minutes?: number;
	auth_allow_multi_session?: number;
};

export type SystemConfig = SystemConfigRow;
export type CreateSystemConfigInput = SystemConfigCreateInput;
export type UpdateSystemConfigInput = SystemConfigUpdateInput;
