/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const UNIT_TABLE = "units";
export const UNIT_COLUMNS = ["id", "code", "name_th", "scope", "store_id"] as const;
export const UNIT_PRIMARY_KEYS = ["id"] as const;

export type UnitRow = {
	id: string;
	code: string;
	name_th: string;
	scope: string;
	store_id: string | null;
};

export type UnitCreateInput = {
	id?: string;
	code: string;
	name_th: string;
	scope?: string;
	store_id?: string | null;
};

export type UnitUpdateInput = {
	code?: string;
	name_th?: string;
	scope?: string;
	store_id?: string | null;
};

export type Unit = UnitRow;
export type CreateUnitInput = UnitCreateInput;
export type UpdateUnitInput = UnitUpdateInput;
