/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const USER_TABLE = "users";
export const USER_COLUMNS = ["id", "email", "name", "password_hash", "created_at", "session_limit", "system_role", "can_create_stores", "max_stores", "can_create_branches", "max_branches_per_store", "created_by", "must_change_password", "password_updated_at", "ui_locale", "client_suspended", "client_suspended_at", "client_suspended_reason", "client_suspended_by"] as const;
export const USER_PRIMARY_KEYS = ["id"] as const;

export type UserRow = {
	id: string;
	email: string;
	name: string;
	password_hash: string;
	created_at: string;
	session_limit: number | null;
	system_role: string;
	can_create_stores: number | null;
	max_stores: number | null;
	can_create_branches: number | null;
	max_branches_per_store: number | null;
	created_by: string | null;
	must_change_password: number;
	password_updated_at: string | null;
	ui_locale: string;
	client_suspended: number;
	client_suspended_at: string | null;
	client_suspended_reason: string | null;
	client_suspended_by: string | null;
};

export type UserCreateInput = {
	id?: string;
	email: string;
	name: string;
	password_hash: string;
	created_at?: string;
	session_limit?: number | null;
	system_role?: string;
	can_create_stores?: number | null;
	max_stores?: number | null;
	can_create_branches?: number | null;
	max_branches_per_store?: number | null;
	created_by?: string | null;
	must_change_password?: number;
	password_updated_at?: string | null;
	ui_locale?: string;
	client_suspended?: number;
	client_suspended_at?: string | null;
	client_suspended_reason?: string | null;
	client_suspended_by?: string | null;
};

export type UserUpdateInput = {
	email?: string;
	name?: string;
	password_hash?: string;
	created_at?: string;
	session_limit?: number | null;
	system_role?: string;
	can_create_stores?: number | null;
	max_stores?: number | null;
	can_create_branches?: number | null;
	max_branches_per_store?: number | null;
	created_by?: string | null;
	must_change_password?: number;
	password_updated_at?: string | null;
	ui_locale?: string;
	client_suspended?: number;
	client_suspended_at?: string | null;
	client_suspended_reason?: string | null;
	client_suspended_by?: string | null;
};

export type User = UserRow;
export type CreateUserInput = UserCreateInput;
export type UpdateUserInput = UserUpdateInput;
