/* eslint-disable */
// Generated by `npm run db:generate-models` from the current database schema.
// Do not edit this file manually.

export const WACONNECTION_TABLE = "wa_connections";
export const WACONNECTION_COLUMNS = ["id", "store_id", "status", "phone_number", "connected_at"] as const;
export const WACONNECTION_PRIMARY_KEYS = ["id"] as const;

export type WaConnectionRow = {
	id: string;
	store_id: string;
	status: string;
	phone_number: string | null;
	connected_at: string | null;
};

export type WaConnectionCreateInput = {
	id?: string;
	store_id: string;
	status?: string;
	phone_number?: string | null;
	connected_at?: string | null;
};

export type WaConnectionUpdateInput = {
	store_id?: string;
	status?: string;
	phone_number?: string | null;
	connected_at?: string | null;
};

export type WaConnection = WaConnectionRow;
export type CreateWaConnectionInput = WaConnectionCreateInput;
export type UpdateWaConnectionInput = WaConnectionUpdateInput;
